
/**************************************************************
 File:                  acxenums.h
 Project:               ACX

 Author:                Automatically generated from
                        AcxDictionary.xml - do not edit !!

**************************************************************
Copyright(C) Siemens AG 2003 All Rights Reserved. Confidential
***************************************************************/

/*! \file  acxenums.h
*/


#ifndef ACXENUMS_H
#define ACXENUMS_H

#define ACX_DICTIONARY_VERSION 0x02100009

enum AcxType
{
    ACXTYPE_INVALID = -1,          /* Invalid value for acx type; Must never be present in a acx/XML*/ 
    ACXTYPE_COMPOUND = 0,          /* Complex Type*/ 
    ACXTYPE_UINT = 1,          /* Unsigned Integer*/ 
    ACXTYPE_INT = 2,          /* Signed Integer*/ 
    ACXTYPE_STRING = 3,          /* String*/ 
    ACXTYPE_FLOAT = 4,          /* IEEE*/ 
    ACXTYPE_EMPTY = 5,          /* empty node*/ 
    ACXTYPE_BINARY = 6          /* Binary data*/ 
};


enum AcxTagId
{
    ACXTAGID_INVALID = -1,          /* Invalid value for acx type; Must never be present in a acx/XML*/ 
    ACXTAGID_ROOT = 0,          /*  Must never be present in XML*/ 
    ACXTAGID_XMLPROCESSINGINSTRUCTION = 1,          /* see chapter 3.3.2 PI and DTD; Must never be present in XML*/ 
    ACXTAGID_XMLDTDDECLARATION = 2,          /* see chapter 3.3.2 PI and DTD; Must never be present in XML*/ 
    ACXTAGID_XMLCOMMENT = 3,          /* see chapter 3.3.6 Reserved XML Tags; Must never be present in XML*/ 
    ACXTAGID_UNKNOWNTAG = 4,          /* see chapter 3.3.4 Unknown ACX-Tag*/ 
    ACXTAGID_ACXCHECKSUM = 5,          /* checksum or hash value to protect files against transmission failures (e.g. CRC check or MDx or SHx); see chapter 3.3.6 Reserved XML Tags; Must never be present in XML*/ 
    ACXTAGID_ACXPROTECTIONKEY = 6,          /* secure hash value to protect the file integrity (protection against unauthorized manipulation); see chapter 3.3.6 Reserved XML Tags; Must never be present in XML*/ 
    ACXTAGID_ACXDICTIONARY = 16,          /* */ 
    ACXTAGID_VERSION = 17,          /* */ 
    ACXTAGID_NAMESPACE = 18,          /* */ 
    ACXTAGID_ACXDEFINITION = 19,          /* */ 
    ACXTAGID_ACXCONTENT = 20,          /* */ 
    ACXTAGID_ACXTYPE = 32,          /* ACX-Definition*/ 
    ACXTAGID_ACXTAGID = 33,          /* ACX-Definition*/ 
    ACXTAGID_ACX_DATATYPE = 34,          /* ACX-Content*/ 
    ACXTAGID_ACX_DISPLAYTYPE = 35,          /* ACX-Content*/ 
    ACXTAGID_ACX_UNIT = 36,          /* ACX-Content*/ 
    ACXTAGID_ACX_REFRESH = 37,          /* ACX-Content*/ 
    ACXTAGID_ACX_LIMITCHECK = 38,          /* ACX-Content*/ 
    ACXTAGID_ACX_ACCESSLEVEL = 39,          /* ACX-Content*/ 
    ACXTAGID_ACX_DRIVEACCESSLEVEL = 40,          /* ACX-Content*/ 
    ACXTAGID_ACX_MEMORYTYPE = 41,          /* ACX-Content*/ 
    ACXTAGID_PREFIX = 64,          /* */ 
    ACXTAGID_CONST = 65,          /* */ 
    ACXTAGID_NAME = 66,          /* */ 
    ACXTAGID_COMMENT = 67,          /* */ 
    ACXTAGID_REFERENCE = 68,          /* */ 
    ACXTAGID_VALUE = 69,          /* */ 
    ACXTAGID_VARIABLE = 128,          /* */ 
    ACXTAGID_IDENTIFIER = 129,          /* */ 
    ACXTAGID_TYPE = 130,          /* */ 
    ACXTAGID_UNIT = 131,          /* */ 
    ACXTAGID_ARRAYLENGTH = 132,          /* */ 
    ACXTAGID_STRINGLENGTH = 133,          /* */ 
    ACXTAGID_DISPLAYTYPE = 134,          /* */ 
    ACXTAGID_SIZE = 135,          /* */ 
    ACXTAGID_NUMBER = 136,          /* */ 
    ACXTAGID_DATATYPE = 137,          /* */ 
    ACXTAGID_MINVALUE = 138,          /* */ 
    ACXTAGID_MAXVALUE = 139,          /* */ 
    ACXTAGID_DEFAULTVALUE = 140,          /* */ 
    ACXTAGID_AUTHOR = 142,          /* */ 
    ACXTAGID_DATE = 143,          /* */ 
    ACXTAGID_INDEX = 144,          /* */ 
    ACXTAGID_ADDRESS = 145,          /* */ 
    ACXTAGID_HEADER = 146,          /* */ 
    ACXTAGID_DESCRIPTION = 147,          /* */ 
    ACXTAGID_ACCESSLEVEL = 148,          /* */ 
    ACXTAGID_LIST = 149,          /* a simple List*/ 
    ACXTAGID_TIMESTAMP = 150,          /* date and time*/ 
    ACXTAGID_BIT = 151,          /* description/meaning of a bit or a bit number (which bit is meant)*/ 
    ACXTAGID_ARRAYLENGTH1 = 152,          /* use to describe multidimensional arrays (dim1) */ 
    ACXTAGID_ARRAYLENGTH2 = 153,          /* use to describe multidimensional arrays (dim2) */ 
    ACXTAGID_FILENAME = 154,          /* path and file name*/ 
    ACXTAGID_SYMBOL = 155,          /* Symbolname*/ 
    ACXTAGID_BITMASK = 156,          /* Bitmask*/ 
    ACXTAGID_UNSET = 157,          /* Bitmask, unset bits*/ 
    ACXTAGID_SET = 158,          /* Bitmask, set bits*/ 
    ACXTAGID_LENGTH = 159,          /* generic length*/ 
    ACXTAGID_DEFAULT = 160,          /* default value*/ 
    ACXTAGID_FORMATVERSION = 161,          /* version of a format structure; it's useful if two different versions in one document are needed; e.g. acx text repository*/ 
    ACXTAGID_FILE = 162,          /* description of a file; e.g. file name, size, ...*/ 
    ACXTAGID_MD5 = 163,          /* MD5 checksum*/ 
    ACXTAGID_MLFB = 164,          /* MLFB of a component*/ 
    ACXTAGID_ENABLE = 165,          /* To enable something*/ 
    ACXTAGID_DISABLE = 166,          /* To disable something*/ 
    ACXTAGID_LANGUAGE = 167,          /* used e.g. to specify a certain language*/ 
    ACXTAGID_AVGVALUE = 168,          /* average value*/ 
    ACXTAGID_KEYWORD = 169,          /* Schluesselwort der NC-Sprache*/ 
    ACXTAGID_PLCDATATYPE = 170,          /* Datentyp der NC-PLC-Variablen in der PLC*/ 
    ACXTAGID_DATAAREAEXTRAINIT = 171,          /* explizite Daten*/ 
    ACXTAGID_FORMAT = 172,          /* */ 
    ACXTAGID_ACC = 1024,          /* AccessDescription*/ 
    ACXTAGID_REFRESH = 1025,          /* */ 
    ACXTAGID_LIMITCHECK = 1026,          /* */ 
    ACXTAGID_LOWERLIMIT = 1027,          /* */ 
    ACXTAGID_UPPERLIMIT = 1028,          /* */ 
    ACXTAGID_DISPLAYFILTER = 1030,          /* */ 
    ACXTAGID_READACCESS = 1031,          /* */ 
    ACXTAGID_WRITEACCESS = 1032,          /* */ 
    ACXTAGID_SAVE = 1033,          /* */ 
    ACXTAGID_EXECUTE = 1034,          /* Executelevel*/ 
    ACXTAGID_FUNCTION = 1035,          /* descendents functions*/ 
    ACXTAGID_DISPLAYGROUP1 = 1036,          /* Anzeigeformat am MMC*/ 
    ACXTAGID_PARAMETERDESCRIPTION = 1037,          /* Parameterbeschreibung*/ 
    ACXTAGID_MEMORYTYPE = 1038,          /* der zur Datenablage verwendete Speichertyp*/ 
    ACXTAGID_UPLOADTYPE = 1039,          /* Ablage im NC-Archiv*/ 
    ACXTAGID_READONLY = 1053,          /* schreibgeschuetzte Variable (MD)*/ 
    ACXTAGID_EXECUTEACCESS = 1055,          /* */ 
    ACXTAGID_SHOWACCESS = 1056,          /* */ 
    ACXTAGID_DELETEACCESS = 1057,          /* */ 
    ACXTAGID_PREDEFFUNCTION = 1040,          /* NC Functions*/ 
    ACXTAGID_PREDEFPROCEDURE = 1041,          /* NC Procedures*/ 
    ACXTAGID_CALLBYREFERENCE = 1042,          /* */ 
    ACXTAGID_RETURNVALUE = 1043,          /* */ 
    ACXTAGID_GCODE = 1044,          /* Number of GCode*/ 
    ACXTAGID_GCODEGROUP = 1045,          /* Number of GCode-Group*/ 
    ACXTAGID_NCADDRESS = 1046,          /* */ 
    ACXTAGID_STOPRE = 1047,          /* Preparation Stop*/ 
    ACXTAGID_OWNERFUNCTION = 1048,          /* see $MN_NC_LANGUAGE_CONFIGURATION*/ 
    ACXTAGID_DATACLASS = 1049,          /* Datenklasse (Siemens, Maschinenhersteller etc.*/ 
    ACXTAGID_DBNUMBER = 1050,          /* DB-Nummer fuer NC-PLC-Variablen.*/ 
    ACXTAGID_DBADRESS = 1051,          /* DB-Adresse fuer NC-PLC-Variablen.*/ 
    ACXTAGID_CYCINFO = 1052,          /* Info, ob eine NC-PLC-Variable zyklisch oder nicht zyklisch aktualisiert wird.*/ 
    ACXTAGID_PLCADRESSTYPE = 1054,          /* PLC-AdressTyp der NC-PLC-Variable (Ausgang, Eingang, Merker, DB etc).*/ 
    ACXTAGID_NC = 1272,          /* Safety- Maschinendatennummer und*/ 
    ACXTAGID_SERVO = 1273,          /* dazugehoerende Antriebparameternummer*/ 
    ACXTAGID_TEA = 1280,          /* machine data*/ 
    ACXTAGID_SYD = 1281,          /* system data*/ 
    ACXTAGID_NCN = 1282,          /* NC-addressidentifier*/ 
    ACXTAGID_GCD = 1283,          /* G-code*/ 
    ACXTAGID_FUN = 1284,          /* predef. functions*/ 
    ACXTAGID_SEA = 1285,          /* setting data*/ 
    ACXTAGID_TOA = 1286,          /* tooldata*/ 
    ACXTAGID_TOC = 1287,          /* toolcarrier data*/ 
    ACXTAGID_TMA = 1288,          /* tool magazine data*/ 
    ACXTAGID_OPT = 1289,          /* optiondata*/ 
    ACXTAGID_ACP = 1290,          /* activel channel parameter*/ 
    ACXTAGID_ACM = 1291,          /* activel channel marker*/ 
    ACXTAGID_GUD = 1292,          /* global user data*/ 
    ACXTAGID_CEC = 1293,          /* cross error compensation*/ 
    ACXTAGID_EEC = 1294,          /* encoder error compensation*/ 
    ACXTAGID_QEC = 1295,          /* quadrant error compensation*/ 
    ACXTAGID_UFR = 1296,          /* user frames*/ 
    ACXTAGID_PRO = 1297,          /* protection areas*/ 
    ACXTAGID_RPA = 1298,          /* R-parameter*/ 
    ACXTAGID_INI = 1299,          /* INI-data*/ 
    ACXTAGID_DPC = 1300,          /* Profibuskonfigurationsdata DP-Config*/ 
    ACXTAGID_DOC = 1301,          /* DriveObjectsConfig*/ 
    ACXTAGID_DOT = 1302,          /* DriveObjectsTypes*/ 
    ACXTAGID_SDC = 1303,          /* Safty-Daten*/ 
    ACXTAGID_EPS = 1304,          /* EPS-Daten*/ 
    ACXTAGID_LUD = 1305,          /* localal user data*/ 
    ACXTAGID_PUD = 1306,          /* programglobal user data*/ 
    ACXTAGID_KYW = 1307,          /* Schluesselworte der NC-Sprache*/ 
    ACXTAGID_NPV = 1308,          /* NC-PLC-Variable*/ 
    ACXTAGID_MAC = 1309,          /* NC-Makros aus _N_SMAC_DEF etc.*/ 
    ACXTAGID_GCI = 1310,          /* ISO-G-Codes*/ 
    ACXTAGID_PROTOKSESSION = 1344,          /* trace session element*/ 
    ACXTAGID_PRIORITYLEVEL = 1345,          /* trace priority level*/ 
    ACXTAGID_ACTIVE = 1346,          /* TRUE when the session is active*/ 
    ACXTAGID_PROTOKEVENT = 1347,          /* trace event element*/ 
    ACXTAGID_CHANNEL = 1348,          /* channel identifier*/ 
    ACXTAGID_DELAY = 1349,          /* number of events before data is recorded*/ 
    ACXTAGID_PROTOKSIGNALLIST = 1350,          /* list of signals to be recorded*/ 
    ACXTAGID_PROTOKTRIGGER = 1355,          /* trace trigger*/ 
    ACXTAGID_MAXFILESIZE = 1356,          /* trace trigger*/ 
    ACXTAGID_IGNORESTOPRE = 1357,          /* trace trigger*/ 
    ACXTAGID_BLOCKTRIGGERS = 1358,          /* trace trigger*/ 
    ACXTAGID_NUMRESTARTS = 1359,          /* trace trigger*/ 
    ACXTAGID_IPOTIME = 1360,          /* trace trigger*/ 
    ACXTAGID_LASTVALUE = 1361,          /* trace trigger*/ 
    ACXTAGID_STATUS = 1362,          /* trace trigger*/ 
    ACXTAGID_NUMMISSED = 1363,          /* trace trigger*/ 
    ACXTAGID_HEADERTYPE = 1364,          /* layout of a record in a protocol file*/ 
    ACXTAGID_AREA = 1351,          /* VarSpec Area*/ 
    ACXTAGID_COLUMN = 1352,          /* VarSpec Column*/ 
    ACXTAGID_ROW = 1353,          /* VarSpec Row*/ 
    ACXTAGID_BLOCK = 1354,          /* VarSpec Block*/ 
    ACXTAGID_VARUNIT = 1376,          /* VarSpec Unit*/ 
    ACXTAGID_NUMROWS = 1377,          /* VarSpec Number of Rows*/ 
    ACXTAGID_INCHMETRIC = 1378,          /* VarSpec InchMetric*/ 
    ACXTAGID_VARSPEC = 1379,          /* BTSS-Variablenbeschreibung*/ 
    ACXTAGID_BTSS = 1380,          /* BTSS-Beschreibung*/ 
    ACXTAGID_CHANGEINFO = 1381,          /* Aenderungsinfo*/ 
    ACXTAGID_FINGERPRINT = 1382,          /* Checksumme fuer ACX-Daten*/ 
    ACXTAGID_ARRAYLENGTH3 = 1383,          /* use to describe multidimensional arrays (dim3) */ 
    ACXTAGID_NCU = 1384,          /* NCU-Beschreibung */ 
    ACXTAGID_SEND = 1385,          /* Send-Beschreibung */ 
    ACXTAGID_RECEIVE = 1386,          /* Receive-Beschreibung */ 
    ACXTAGID_DESTINATION = 1387,          /* Ziel-NCU */ 
    ACXTAGID_SOURCE = 1388,          /* Quell-NCU */ 
    ACXTAGID_LINK = 1389,          /* Datenart = NCU-Linkbeschreibung */ 
    ACXTAGID_MACRO = 1390,          /* Compound-Tack fuer (NC-)Makros aus _N_SMAC_DEF etc.*/ 
    ACXTAGID_CONTENT = 1391,          /* (Makro-)Definition aus _N_SMAC_DEF etc.*/ 
    ACXTAGID_BUFFERSIZEDEFAULT = 1392,          /* Default Groesse des Puffers fuer NCU-LINK*/ 
    ACXTAGID_BUFFERNUMBER = 1393,          /*  Puffernummer fuer NCU-LINK*/ 
    ACXTAGID_CONNECT = 1394,          /*  Verbindungsdaten fuer NCU-LINK*/ 
    ACXTAGID_DATACYCLETIME = 1395,          /*  Zeit fur einen NCU-LINK-Zyklus*/ 
    ACXTAGID_EEPDATA = 2047,          /* root element Eprom saved motorsets*/ 
    ACXTAGID_FILES = 2048,          /* root element of FILES.ACX; includes a specific checksum of all files on cf card*/ 
    ACXTAGID_CARDVERSION = 2049,          /* overall version of CF card within FILES.ACX; it's not always necessarily the same as fw version of rt software*/ 
    ACXTAGID_DRIVEDATA = 2050,          /* */ 
    ACXTAGID_MOTORLIST = 2051,          /* */ 
    ACXTAGID_SRMOTOR = 2052,          /* */ 
    ACXTAGID_SLMOTOR = 2053,          /* */ 
    ACXTAGID_ARMOTOR = 2054,          /* */ 
    ACXTAGID_ENCODERLIST = 2055,          /* */ 
    ACXTAGID_ENCODER = 2056,          /* */ 
    ACXTAGID_BRAKELIST = 2057,          /* */ 
    ACXTAGID_SRBRAKE = 2058,          /* */ 
    ACXTAGID_MOTSRM = 2059,          /* Root Element for File with list of synchronous rotatory motors*/ 
    ACXTAGID_MOTSLM = 2060,          /* Root Element for File with list of synchronous linear motors*/ 
    ACXTAGID_MOTARM = 2061,          /* Root Element for File with list of asynchronous rotatory motors*/ 
    ACXTAGID_REQUIRESVERSION = 2062,          /* Minimal Firmware Version with which a motorlist is valid*/ 
    ACXTAGID_ENCDATA = 2063,          /* Root Element for File with list of encoder descriptions*/ 
    ACXTAGID_FILTERDATA = 2064,          /* Root Element for files with list of filter data descriptions*/ 
    ACXTAGID_FILTERLIST = 2065,          /* list of filter data elements*/ 
    ACXTAGID_FILTER = 2066,          /* description of one filter element*/ 
    ACXTAGID_INFEEDDATA = 2067,          /* Root Element for files with list of infeed data descriptions*/ 
    ACXTAGID_INFEEDLIST = 2068,          /* list of infeed data elements*/ 
    ACXTAGID_INFEED = 2069,          /* description of one infeed element*/ 
    ACXTAGID_INDUCTORDATA = 2070,          /* Root Element for files with list of inductor data descriptions*/ 
    ACXTAGID_INDUCTORLIST = 2071,          /* list of inductor data elements*/ 
    ACXTAGID_INDUCTOR = 2072,          /* description of one inductor element*/ 
    ACXTAGID_GEARLIST = 2073,          /* list of gear elements*/ 
    ACXTAGID_ENCODERGEAR = 2074,          /* description of one gear element*/ 
    ACXTAGID_DAT_BEAR = 2075,          /* root element for files with list of bearing descriptions*/ 
    ACXTAGID_BEARING = 2076,          /* description of one bearing*/ 
    ACXTAGID_CFG_BEAR = 2077,          /* root element for files with list of bearing configurations*/ 
    ACXTAGID_CFGBEARING = 2078,          /* description of one bearing configuration*/ 
    ACXTAGID_SPINDLEDATA = 2079,          /* root tag of spindle data description files*/ 
    ACXTAGID_SPINDLELIST = 2080,          /* a spindle list within a spindle data description file*/ 
    ACXTAGID_SPINDLE = 2081,          /* description of a spindle*/ 
    ACXTAGID_ENC_GEAR = 2082,          /* root element for files with list of encoder gear configurations*/ 
    ACXTAGID_TYP_BEAR = 2083,          /* root element for files with list of bearing type descriptions*/ 
    ACXTAGID_BEARINGTYPE = 2084,          /* description of one bearing type*/ 
    ACXTAGID_CFG_ENC = 2085,          /* root element for files with list of encoder configurations*/ 
    ACXTAGID_CFGENCODER = 2086,          /* description of one encoder configuration*/ 
    ACXTAGID_SPINDLESET = 2087,          /* description of the spindle parameter settings*/ 
    ACXTAGID_DATASETHANDLING = 2088,          /* form of data set handling, like DDS, MDS, EDS*/ 
    ACXTAGID_PARALLELCONNECTABLE = 2089,          /* form of parallel connection*/ 
    ACXTAGID_INSTANCECHECKSUM = 2090,          /* checksum of instance oriented acx description file, e.g. PDI file*/ 
    ACXTAGID_INSTANCEGUID = 2091,          /* GUID of instance oriented acx description file, e.g. PDI file*/ 
    ACXTAGID_USEGUID = 2092,          /* used GUID?*/ 
    ACXTAGID_USED = 2093,          /* describes used enitities/bit/etc. within an element/value/bitmask/etc.*/ 
    ACXTAGID_CONFIGGROUP = 2094,          /* compound element for multiple ConfigurationGroup's*/ 
    ACXTAGID_CONSTCONFIG = 2095,          /* marks all static/const configuration bits - which can't be changed from default value*/ 
    ACXTAGID_CONNECTOR = 2096,          /* describes a connection between different CU types; e.g. CU_I - CX32*/ 
    ACXTAGID_PROPERTIES = 2097,          /* Properties; e.g. of a CU connection*/ 
    ACXTAGID_DESCSTRUCTUREPARAM = 2098,          /* PD-Struktur-bestimmende Parameter innerhalb der PS-Datei*/ 
    ACXTAGID_EXISTSINCONFIGGROUP = 2099,          /* expresses in which conifguration group a parameter exists*/ 
    ACXTAGID_SAVEPARAMETER = 2100,          /* */ 
    ACXTAGID_PARAMETER = 2101,          /* */ 
    ACXTAGID_PARAMETERLIST = 2102,          /* */ 
    ACXTAGID_PARAMETERS = 2103,          /* */ 
    ACXTAGID_DOTYPE = 2104,          /* */ 
    ACXTAGID_DEFINITIONS = 2105,          /* */ 
    ACXTAGID_CONFIGURATIONS = 2106,          /* */ 
    ACXTAGID_CONFIGURATIONDEF = 2107,          /* DO class configuration*/ 
    ACXTAGID_ATTRIBUTESFIX = 2108,          /* obsolete*/ 
    ACXTAGID_ATTRIBUTESTO1 = 2109,          /* obsolete*/ 
    ACXTAGID_ATTRIBUTESTO2 = 2110,          /* obsolete*/ 
    ACXTAGID_ATTRIBUTESHIDE = 2111,          /* obsolete*/ 
    ACXTAGID_ARRAY = 2112,          /* */ 
    ACXTAGID_DYNARRAY = 2113,          /* */ 
    ACXTAGID_CONFIGURATION = 2114,          /* */ 
    ACXTAGID_CONFIGNR = 2115,          /* */ 
    ACXTAGID_VALIDVALUES = 2116,          /* */ 
    ACXTAGID_RANGE = 2117,          /* */ 
    ACXTAGID_ENUM = 2118,          /* */ 
    ACXTAGID_ATTRIBUTES = 2119,          /* */ 
    ACXTAGID_ATTRIBUTEDEF = 2120,          /* */ 
    ACXTAGID_GUID = 2121,          /* GUID for starter*/ 
    ACXTAGID_MAJOR = 2122,          /* major version*/ 
    ACXTAGID_MINOR = 2123,          /* minor version*/ 
    ACXTAGID_DEVICEGUID = 2124,          /* device GUID for starter*/ 
    ACXTAGID_DEVICEMAJOR = 2125,          /* device major version*/ 
    ACXTAGID_DEVICEMINOR = 2126,          /* device minor version*/ 
    ACXTAGID_DRIVEACCESSLEVEL = 2127,          /* */ 
    ACXTAGID_CONSTRUCTION = 2128,          /* means physical construction of a drive device, e.g. cabinet or chassis*/ 
    ACXTAGID_DOCATEGORY = 2129,          /* drive object category; e.g. terminal module, ctrl object, ...*/ 
    ACXTAGID_VIEW = 2130,          /* application specific view; e.g. of a parameter description*/ 
    ACXTAGID_USEDCONFIG = 2131,          /* is used to describe a valid configuration for SINAMICS*/ 
    ACXTAGID_STARTUP = 2132,          /* is used to describe a valid configuration for SINAMICS*/ 
    ACXTAGID_EXCLUSION = 2133,          /* is used to describe a valid configuration for SINAMICS*/ 
    ACXTAGID_PRECONDITION = 2134,          /* is used to describe a valid configuration for SINAMICS*/ 
    ACXTAGID_APPLIESTO = 2135,          /* is used to describe a valid configuration for SINAMICS*/ 
    ACXTAGID_CONDITIONMASK = 2136,          /* is used to describe a valid configuration for SINAMICS*/ 
    ACXTAGID_EXISTSINCONFIG = 2137,          /* expresses in which configuration a parameter exists*/ 
    ACXTAGID_ATTRIBUTES1 = 2138,          /* attributes of a parameter*/ 
    ACXTAGID_ATTRIBUTES2 = 2139,          /* attributes of a parameter*/ 
    ACXTAGID_ATTRIBUTES3 = 2140,          /* attributes of a parameter*/ 
    ACXTAGID_ATTRIBUTES4 = 2141,          /* attributes of a parameter*/ 
    ACXTAGID_INTERNALATTRIBUTES = 2142,          /* internal attributes of a parameter; these attributes are only used by runtime system and should NOT be used by the clients*/ 
    ACXTAGID_MODIFICATION = 2143,          /* modifications of a parameter*/ 
    ACXTAGID_PD = 2144,          /* root element of a parameter description file*/ 
    ACXTAGID_DOBASIS = 2145,          /* compound tag for basis file header information*/ 
    ACXTAGID_DOCLASS = 2146,          /* DO-Type*/ 
    ACXTAGID_DOVIEW = 2147,          /* specifies a application specific view*/ 
    ACXTAGID_CONFIGURATIONGROUP = 2148,          /* specifies a configuration group*/ 
    ACXTAGID_POSITION = 2149,          /* e.g. position within a bit array*/ 
    ACXTAGID_PARAMETERMACRO = 2150,          /* */ 
    ACXTAGID_ERRORLEVEL = 2151,          /* */ 
    ACXTAGID_VALIDFOR = 2152,          /* e.g. valid for parameter p15*/ 
    ACXTAGID_DRIVEOBJECT = 2153,          /* */ 
    ACXTAGID_BICOREF = 2154,          /* */ 
    ACXTAGID_BICOSRC = 2155,          /* */ 
    ACXTAGID_FACTORYSETTING = 2156,          /* */ 
    ACXTAGID_MODE = 2157,          /* here: factory setting mode*/ 
    ACXTAGID_DEVICE = 2158,          /* */ 
    ACXTAGID_AUTHORIZED = 2159,          /* Signs an authorized macro; -> such macros should have a checksum*/ 
    ACXTAGID_WAITUNTIL = 2160,          /* a syntax element within macros; wait for an event ...*/ 
    ACXTAGID_WAITUNTILNOT = 2161,          /* a syntax element within macros; wait for the condition to disappear*/ 
    ACXTAGID_MODELL3 = 2162,          /* thermical motor model I2tA*/ 
    ACXTAGID_TEMPERATURMODELLLIST = 2163,          /* list of possible thermical motor models*/ 
    ACXTAGID_ARLDMOTOR = 2164,          /* */ 
    ACXTAGID_MOTARMLD = 2165,          /* Root Element for File with list of asynchronous rotatory motors ld*/ 
    ACXTAGID_THERMMOTMOD = 2166,          /* Root Element for File with list of thermical motor models 3*/ 
    ACXTAGID_MAPPING = 2167,          /* Root Element for File with mapping of motor and thermal modell 3*/ 
    ACXTAGID_MAPPINGLIST = 2168,          /* list of possible mappings*/ 
    ACXTAGID_MAPPINGENTRY = 2169,          /* mapping*/ 
    ACXTAGID_PREFERREDBICOS = 2170,          /* BIxxxxxx.acx files are documents for e.g. Starter/HMI that includes all preferred/wise BiCo connections of all BiCo parameters*/ 
    ACXTAGID_ALLBITS = 2171,          /* AllBits means all bits (of a bitfield) are connectable*/ 
    ACXTAGID_ALLINDICES = 2172,          /* AllIndices means all indices (of a param array) are connectable*/ 
    ACXTAGID_MODELL3DB = 2180,          /* thermical motor model I2TA from motor data base*/ 
    ACXTAGID_RSMOTOR = 2181,          /* */ 
    ACXTAGID_MOTRSM = 2182,          /* Root Element for File with list of reluctant motors*/ 
    ACXTAGID_DATA_BRAKE = 2183,          /* Root Element for File with list of breaks*/ 
    ACXTAGID_CFG_BRK = 2184,          /* Root element for files with list of brake configurations*/ 
    ACXTAGID_CFGBRAKE = 2185,          /* Description of one brake configuration*/ 
    ACXTAGID_RESMOTOR = 2186,          /* */ 
    ACXTAGID_MOTRESM = 2187,          /* Root Element for File with list of reluctant motors*/ 
    ACXTAGID_CFG_ENC_GEAR = 2188,          /* root element for encoder gear configuraion files*/ 
    ACXTAGID_CFGENCODERGEAR = 2189,          /* description of one encoder gear configuraion*/ 
    ACXTAGID_CHANGEUNIT = 2190,          /* in case of p15 macro execution prevent setting p10 to 0*/ 
    ACXTAGID_CD = 2199,          /* Root tag for CD files containing configuration data*/ 
    ACXTAGID_ALARMLIST = 2200,          /* */ 
    ACXTAGID_ALARM = 2201,          /* */ 
    ACXTAGID_MESSAGEDESCRIPTION = 2202,          /* message (fault/warning) dsc list*/ 
    ACXTAGID_MESSAGE = 2203,          /* dsc of one message (fault/warning)*/ 
    ACXTAGID_REACTION = 2204,          /* stop reaction of a fault*/ 
    ACXTAGID_ACKNOWLEDGE = 2205,          /* acknowledge method of a fault*/ 
    ACXTAGID_ADDITIONALINFOTYPE = 2206,          /* data type of fault/warning value*/ 
    ACXTAGID_POSSIBLE = 2207,          /* possible values*/ 
    ACXTAGID_FD = 2208,          /* root element of a message (fault) description file*/ 
    ACXTAGID_OA = 2209,          /* OA applications*/ 
    ACXTAGID_APPLICATION = 2210,          /* description of one OA application*/ 
    ACXTAGID_OAAPPLSYMBOL = 2211,          /* unique version-independent OA application name*/ 
    ACXTAGID_INSTANCE = 2212,          /* means, this description file is instance oriented*/ 
    ACXTAGID_SUBSTITUTION = 2213,          /* act replacing*/ 
    ACXTAGID_ADDON = 2214,          /* act expanding*/ 
    ACXTAGID_MESSAGECATEGORY = 2215,          /* possible message categories*/ 
    ACXTAGID_DOCLASSREFPAR = 2216,          /* possible message categories; used e.g. in SD file*/ 
    ACXTAGID_DOCLASSREFMSG = 2217,          /* possible message categories; used e.g. in SD file*/ 
    ACXTAGID_CLASS = 2218,          /* class*/ 
    ACXTAGID_INDDATA = 2220,          /* Typ Specific Indiviual Motor Data*/ 
    ACXTAGID_COGTRQLIST = 2221,          /* Cogging Torque Compensation List*/ 
    ACXTAGID_COGTRQDATA = 2222,          /* Cogging Torque Compensation Data*/ 
    ACXTAGID_UD = 2251,          /* root element of file UD.ACX*/ 
    ACXTAGID_UNITSWITCH = 2252,          /* unit switch description*/ 
    ACXTAGID_SELECTION = 2253,          /* selection list*/ 
    ACXTAGID_PHYSICALUNIT = 2254,          /* physical unit*/ 
    ACXTAGID_UNITGROUP = 2255,          /* unit group*/ 
    ACXTAGID_FORMULAREFERENCE = 2256,          /* formula reference*/ 
    ACXTAGID_FORMULA = 2257,          /* description of a formula*/ 
    ACXTAGID_FACTOR = 2258,          /* factor in formula*/ 
    ACXTAGID_SCALINGATTRIBUTE = 2259,          /* reference to bico scaling formula in PD file*/ 
    ACXTAGID_PHYSICALUNITDESCRIPTION = 2260,          /* Description of a physical Unit, e.g. Length*/ 
    ACXTAGID_PHYSICALUNITDESCRIPTIONLIST = 2261,          /* List of descriptions of physical Units*/ 
    ACXTAGID_FACTORINDEXED = 2262,          /* factor in formula which is index specific in this case*/ 
    ACXTAGID_INDEXPARAMETER = 2263,          /* The number of the parameter which contains the index of the parameter referenced by element factor*/ 
    ACXTAGID_CONFIGURATIONDEF1 = 2270,          /* DO class configuration (2nd configuration word)*/ 
    ACXTAGID_CONFIGURATIONDEF2 = 2271,          /* DO class configuration (3rd configuration word)*/ 
    ACXTAGID_CONFIGURATIONDEF3 = 2272,          /* DO class configuration (4th configuration word)*/ 
    ACXTAGID_EXISTSINCONFIG1 = 2273,          /* expresses in which configuration a parameter exists (2nd configuration word)*/ 
    ACXTAGID_EXISTSINCONFIG2 = 2274,          /* expresses in which configuration a parameter exists (3rd configuration word)*/ 
    ACXTAGID_EXISTSINCONFIG3 = 2275,          /* expresses in which configuration a parameter exists  (4th configuration word)*/ 
    ACXTAGID_MODIFICATION1 = 2276,          /* modifications of a parameter (2nd configuration word)*/ 
    ACXTAGID_MODIFICATION2 = 2277,          /* modifications of a parameter (3rd configuration word)*/ 
    ACXTAGID_MODIFICATION3 = 2278,          /* modifications of a parameter (4th configuration word)*/ 
    ACXTAGID_PG = 2280,          /* root element for parameter group file (icd_ACX_PG)*/ 
    ACXTAGID_PARAMETERGROUPS = 2281,          /* container for parameter group definitions (icd_ACX_PG)*/ 
    ACXTAGID_GROUP = 2282,          /* parameter group (icd_ACX_PG and icd_ACX_PD)*/ 
    ACXTAGID_GROUPTYPE = 2283,          /* parameter group type (icd_ACX_PG and icd_ACX_PD)*/ 
    ACXTAGID_COMPONENTSLIST = 2300,          /* list of HW components*/ 
    ACXTAGID_COMPONENT = 2301,          /* a HW component*/ 
    ACXTAGID_AUTHENTICATION = 2349,          /* authentication method to mark the oa-application's ACX- and ELF files, e.g. type 1, 2, 3, 4 etc.*/ 
    ACXTAGID_SYSTEMDESCRIPTION = 2350,          /* system description*/ 
    ACXTAGID_SD = 2351,          /* root element of a system description file*/ 
    ACXTAGID_INTERFACEVERSION = 2352,          /* interface version; e.g. oa interface*/ 
    ACXTAGID_COMPATIBILITY = 2353,          /* used for compatibility rules*/ 
    ACXTAGID_MINVERSION = 2354,          /* minimal version in a version range*/ 
    ACXTAGID_MAXVERSION = 2355,          /* maximal version in a version range*/ 
    ACXTAGID_PACKAGEID = 2356,          /* package identifier*/ 
    ACXTAGID_METHODID = 2357,          /* method identifier*/ 
    ACXTAGID_ABSOLUTE = 2358,          /* signs a absolute addressing scheme*/ 
    ACXTAGID_RELATIVE = 2359,          /* signs a relative addressing scheme*/ 
    ACXTAGID_SYSTEM = 2360,          /* specifies the systems in which a oa application is valid*/ 
    ACXTAGID_SYSTEMCATEGORY = 2361,          /* system category; e.g. standalone, integrated, cabinet*/ 
    ACXTAGID_BASE = 2362,          /* describes the base system*/ 
    ACXTAGID_MAXINSTANCES = 2363,          /* max instances possible e.g. per DO type*/ 
    ACXTAGID_CONFIGURATIONRT = 2364,          /* resulting DO class configuration effective in RT system*/ 
    ACXTAGID_ES = 2365,          /* used e.g. to describe a compound of tags which are relevant only in engineering system*/ 
    ACXTAGID_LICENSE = 2366,          /* used e.g. to sign the existence of the license option*/ 
    ACXTAGID_DISPLAYNAME = 2367,          /* display name for ES tools; e.g. if it's different from identifier name*/ 
    ACXTAGID_MININSTANCES = 2368,          /* min instances possible e.g. per DO type*/ 
    ACXTAGID_EXTERNALVERSION = 2369,          /* external version of a device used in ES*/ 
    ACXTAGID_CPUTYPE = 2370,          /* processor type of a specific device*/ 
    ACXTAGID_HIDE = 2371,          /* used as an attribute, e.g. for an only-internal oa application: Hide oa appl*/ 
    ACXTAGID_NOTDELETABLE = 2372,          /* used as an attribute, to sign an oa application as undeletable on CF card in case of "OEM Werkseinstellung"*/ 
    ACXTAGID_DODERIVED = 2373,          /* used as an attribute, to sign a DO View with extended derivations possibilities (e.g. derivations of texts)*/ 
    ACXTAGID_DEVELOPMENT = 2374,          /* used to sign parts of ACX documents as "still under construction - do not show on user interface (docu, ES)", e.g. used for new devices in sd file*/ 
    ACXTAGID_PRELIMINARY = 2375,          /* similar to Development, used to sign parts of ACX documents as "still under construction - do not show on user interface (docu, ES)", e.g. used for new devices in sd file*/ 
    ACXTAGID_BICODISPLAY = 2376,          /* Interne Verschaltungen (BiCo) nicht anzeigen (für TM54 slave); for PD files*/ 
    ACXTAGID_PROFIDRIVEINPZD = 2377,          /* DOClasse hat zyklische Daten und wird in p978 eingetragen; for PD files*/ 
    ACXTAGID_GLOBALRESOURCE = 2378,          /* Globale Resourcen, welche von OA-Applikation genutzt werden*/ 
    ACXTAGID_NOTPDOWNLOAD = 2379,          /* Verhalten des Technologiepaket-Dialogs*/ 
    ACXTAGID_NOTPUPLOAD = 2380,          /* Verhalten des Technologiepaket-Dialogs*/ 
    ACXTAGID_SEGMENTEDTPDL = 2381,          /* Segmentierter TPDL wird unterstuetzt*/ 
    ACXTAGID_SOFTACTIVATEOAELF = 2382,          /* Power Off/On nach dem OA-Technologiepaket-Download nicht erforderlich*/ 
    ACXTAGID_CUSTOMINTERFACEDEFINITION = 2383,          /* DCB Interface Definition or similar interface description between different OA applications, compatibility version range, ...*/ 
    ACXTAGID_CUSTOMINTERFACEUSE = 2384,          /* Use of DCB Interface or similar interface use between different OA applications*/ 
    ACXTAGID_COMMINTERFACE = 2385,          /* Communication Interface description like CBE20, CBE25 or Profibus, e.g. slot count, telegram length*/ 
    ACXTAGID_MAXSLOTCOUNT = 2386,          /* max slot count of a specific Communication Interface*/ 
    ACXTAGID_MAXINPUTLENGTH = 2387,          /* max input telegram length of a specific Communication Interface*/ 
    ACXTAGID_MAXOUTPUTLENGTH = 2388,          /* max output telegram length of a specific Communication Interface*/ 
    ACXTAGID_DOCUPARTS = 2389,          /* description of docu part lists*/ 
    ACXTAGID_FORCECODELOAD = 2390,          /* Force loading of OA code, without need of OA activation, e.g. if functionalities in the OA-Application are used without activation*/ 
    ACXTAGID_DELTAVERSION = 2391,          /* version of delta description data from view editor*/ 
    ACXTAGID_CONFIGURATIONRT1 = 2392,          /* resulting DO class configuration effective in RT system (2nd config word)*/ 
    ACXTAGID_CONFIGURATIONRT2 = 2393,          /* resulting DO class configuration effective in RT system (3rd config word)*/ 
    ACXTAGID_CONFIGURATIONRT3 = 2394,          /* resulting DO class configuration effective in RT system (4th config word)*/ 
    ACXTAGID_INTERFACEVERSIONES = 2395,          /* oa interface version which is used for ES; see InterfaceVersion*/ 
    ACXTAGID_ADDONOA = 2396,          /* mandatory add on OAs*/ 
    ACXTAGID_VERSIONEDASPECT = 2397,          /* additional optional versioned aspects e.g. of OA applications, like DCB-Lib version, Simulink version*/ 
    ACXTAGID_EXCLUDEFROMFIRMWAREUPGRADE = 2398,          /* attribute of OA applicatons like DCC, which shouldn't be upgrated synchrously with FW of base system*/ 
    ACXTAGID_INVISIBLE = 2399,          /* Used to encapsulate implementation-specific information which is irrelevant for clients*/ 
    ACXTAGID_MESSAGENAMES = 2400,          /* root element for FN-files*/ 
    ACXTAGID_TEXT = 2401,          /* Text*/ 
    ACXTAGID_SHORTNAME = 2402,          /* short name*/ 
    ACXTAGID_CAUSE = 2403,          /* cause of the fault/warning*/ 
    ACXTAGID_REMEDY = 2404,          /* remedy of the fault/warning*/ 
    ACXTAGID_TEXTREPOSITORY = 2405,          /* root element of a text repository*/ 
    ACXTAGID_OFFSET = 2406,          /* an offset, e.g. byte offset*/ 
    ACXTAGID_TEXTLIST = 2407,          /* a text list within a text repository*/ 
    ACXTAGID_ADDITIONALINFO = 2408,          /* text regarding to the additional info of an alarm*/ 
    ACXTAGID_PN = 2409,          /* root element of a parameter name file*/ 
    ACXTAGID_PH = 2410,          /* root element of a parameter help file*/ 
    ACXTAGID_FN = 2411,          /* root element of a message (fault) name file*/ 
    ACXTAGID_FH = 2412,          /* root element of a message (fault) help file*/ 
    ACXTAGID_MAXREFERENCE = 2413,          /* highest number of a reference*/ 
    ACXTAGID_REFERENCETABLE = 2414,          /* List with references*/ 
    ACXTAGID_CONFIGURATIONBIT = 2415,          /* description of a configuration (bit)*/ 
    ACXTAGID_BITPOS = 2416,          /* to address a bit position*/ 
    ACXTAGID_PARAMETERNAMES = 2417,          /* textual description of one parameter*/ 
    ACXTAGID_BITFIELD = 2418,          /* description of a bit field*/ 
    ACXTAGID_NIBBLE = 2419,          /* description of a nibble*/ 
    ACXTAGID_DOCATEGORYNAME = 2420,          /* description of a DO category*/ 
    ACXTAGID_DOCLASSNAME = 2421,          /* DO class name*/ 
    ACXTAGID_ABBREVIATION = 2422,          /* abbreviation*/ 
    ACXTAGID_DIALOGNAME = 2423,          /* dialog name*/ 
    ACXTAGID_PARAMETERHELP = 2424,          /* compound for one parameter help info*/ 
    ACXTAGID_RECOMMENDATIONS = 2425,          /* recommendations*/ 
    ACXTAGID_DANGER = 2426,          /* danger*/ 
    ACXTAGID_WARNING = 2427,          /* warning*/ 
    ACXTAGID_CAUTIONHIGH = 2428,          /* caution high*/ 
    ACXTAGID_CAUTIONLOW = 2429,          /* caution low*/ 
    ACXTAGID_ATTENTION = 2430,          /* attention*/ 
    ACXTAGID_NOTE = 2431,          /* note*/ 
    ACXTAGID_FUNCTIONPLAN = 2432,          /* function plan*/ 
    ACXTAGID_DEPENDENCY = 2433,          /* dependency*/ 
    ACXTAGID_MESSAGEREFLIST = 2434,          /* message reference list*/ 
    ACXTAGID_PARAMREFLIST = 2435,          /* parameter reference list*/ 
    ACXTAGID_MESSAGEHELP = 2436,          /* compound for one message help info*/ 
    ACXTAGID_CAUSEPARAMREFLIST = 2437,          /* cause parameter reference list*/ 
    ACXTAGID_REMEDYPARAMREFLIST = 2438,          /* remedy parameter reference list*/ 
    ACXTAGID_DOCLASSSHORTNAME = 2439,          /* short name of this DO class*/ 
    ACXTAGID_MT = 2440,          /* root element of miscellaneous text files (param errors, unit names)*/ 
    ACXTAGID_PARAMETRIZATIONERRORLIST = 2441,          /* list element for textuell description of parametrization error codes*/ 
    ACXTAGID_PARAMETRIZATIONERRORDESCRIPTION = 2442,          /* textuell description of parametrization error codes*/ 
    ACXTAGID_S7VALUE = 2443,          /* S7 value of an error code*/ 
    ACXTAGID_UNITDESCRIPTIONLIST = 2444,          /* list of textuell description of units*/ 
    ACXTAGID_UNITDESCRIPTION = 2445,          /* textuell description of a unit*/ 
    ACXTAGID_BASEREFERENCE = 2446,          /* base text reference per oa application*/ 
    ACXTAGID_ENDREFERENCE = 2447,          /* end text reference per oa application*/ 
    ACXTAGID_DV = 2448,          /* root element for dynamic lock files*/ 
    ACXTAGID_LOCKTEXT = 2449,          /* a dynamic lock text*/ 
    ACXTAGID_EXAMPLE = 2450,          /* example use case; e.g. can be used in PH files*/ 
    ACXTAGID_CONFIGURATIONERRORLIST = 2451,          /* list of configuration failures, e.g. YDB protocol*/ 
    ACXTAGID_CONFIGURATIONERRORDESCRIPTION = 2452,          /* description of a configuration failure, e.g. YDB protocol*/ 
    ACXTAGID_LIMITEDDESCRIPTION = 2453,          /* similar to Description but more compact*/ 
    ACXTAGID_LIMITEDCAUSE = 2454,          /* similar to Cause but more compact*/ 
    ACXTAGID_LIMITEDREMEDY = 2455,          /* similar to Remedy but more compact*/ 
    ACXTAGID_INSTANCENAME = 2456,          /* instance name of a DO used e.g. as plan name of DCC PDI files*/ 
    ACXTAGID_BN = 2457,          /* root element of BACnet object description list files (BN - BACnet names)*/ 
    ACXTAGID_BACNETOBJECTDESCRIPTIONLIST = 2458,          /* BACnet object description list*/ 
    ACXTAGID_BACNETOBJECTDESCRIPTION = 2459,          /* BACnet object description element*/ 
    ACXTAGID_CONFIGURATIONBIT1 = 2460,          /* description of a configuration (bit) (2nd configuration word)*/ 
    ACXTAGID_CONFIGURATIONBIT2 = 2461,          /* description of a configuration (bit) (3rd configuration word)*/ 
    ACXTAGID_CONFIGURATIONBIT3 = 2462,          /* description of a configuration (bit) (4th configuration word)*/ 
    ACXTAGID_LOADGEAR = 2463,          /* description of one load gear element*/ 
    ACXTAGID_LOAD_GEAR = 2464,          /* root element for files with list of load gear descriptions*/ 
    ACXTAGID_DATA_TEMPERATURE_SENSOR = 2465,          /* root element for files with list of temperature sensor descriptions*/ 
    ACXTAGID_TEMPERATURESENSOR = 2466,          /* description of one temperature sensor*/ 
    ACXTAGID_CFG_TSR = 2467,          /* root element for motor-temp sensor configuraion files*/ 
    ACXTAGID_CFGTEMPERATURESENSOR = 2468,          /* description of one motor-temp sensor configuraion*/ 
    ACXTAGID_LN = 2469,          /* root element of license options*/ 
    ACXTAGID_LOADGEARRULES = 2470,          /* description of one load gear rules element*/ 
    ACXTAGID_LOAD_GEAR_RULES = 2471,          /* root element for files with list of load gear rules descriptions*/ 
    ACXTAGID_DOLIST = 2472,          /* root element for DOs in the system(ADO/SDO)*/ 
    ACXTAGID_INFO = 2473,          /* root element for DOList and ComponentsList*/ 
    ACXTAGID_RUNTIME = 2500,          /* root element of RUNTIME.ACX - cyclic method attributes for runtime messurement things*/ 
    ACXTAGID_METHODDESCRIPTION = 2501,          /* discribes one complete method (min, max, avg time)*/ 
    ACXTAGID_FIRST = 2502,          /* first instance?*/ 
    ACXTAGID_MINADAPTION = 2503,          /* Korrekturfaktor Gesamtzeitscheiben- zu Summe der Einzelmessungen, min-Laufzeit*/ 
    ACXTAGID_AVGADAPTION = 2504,          /* Korrekturfaktor Gesamtzeitscheiben- zu Summe der Einzelmessungen, avg-Laufzeit*/ 
    ACXTAGID_MAXADAPTION = 2505,          /* Korrekturfaktor Gesamtzeitscheiben- zu Summe der Einzelmessungen, max-Laufzeit*/ 
    ACXTAGID_IRQMINLATENCY = 2506,          /* Minimale Interruptlatenz*/ 
    ACXTAGID_IRQMAXJITTER = 2507,          /* Maximaler Jitter der Interruptlatenz*/ 
    ACXTAGID_IRQMINLATENCYD410 = 2508,          /* Minimale Interruptlatenz D410*/ 
    ACXTAGID_IRQMAXJITTERD410 = 2509,          /* Maximaler Jitter der Interruptlatenz D410*/ 
    ACXTAGID_PLLADJFACTOR = 2510,          /* Geschwindigkeit, mit der die PLL die Takte an einen externen Takt anpasst*/ 
    ACXTAGID_IRQOVERHEAD = 2511,          /* Zeit, die durch einen Zeitscheibeninterrupt vergeht*/ 
    ACXTAGID_MAXADJFACTORFIRST = 2512,          /* Faktor zwischen berechneter und gemessener Maximalsumme über eine Zeitscheibe,erste Anmeldung*/ 
    ACXTAGID_MAXADJFACTORNEXT = 2513,          /* Faktor zwischen berechneter und gemessener Maximalsumme über eine Zeitscheibe,Folgeanmeldung*/ 
    ACXTAGID_BACKGROUNDLOAD = 2514,          /* Hintergrundlast*/ 
    ACXTAGID_DQ = 2515,          /* DQ relevant ?*/ 
    ACXTAGID_PMEMORY = 2550,          /* root element of PMEMORY.ACX - backup file for NVRAM data*/ 
    ACXTAGID_DATAONLINE = 2551,          /* NVRAM online data for DSAC*/ 
    ACXTAGID_DATAPDWN = 2552,          /* NVRAM power down data for DSAC*/ 
    ACXTAGID_CN = 2560,          /* root element of a command name file*/ 
    ACXTAGID_CI = 2561,          /* root element of a command definition file*/ 
    ACXTAGID_COMMAND = 2562,          /* definition of a command*/ 
    ACXTAGID_VISIBILITY = 2563,          /* */ 
    ACXTAGID_ARGUMENT = 2564,          /* definition of a command argument*/ 
    ACXTAGID_DONE = 2565,          /* definition of a command response in case of success*/ 
    ACXTAGID_ERROR = 2566,          /* definition of a command response in case of error*/ 
    ACXTAGID_COUNT = 2567,          /* */ 
    ACXTAGID_OPTIONAL = 2568,          /* Marker for optional tags*/ 
    ACXTAGID_TRACEDATA = 2580,          /* TraceData tag for grouping trace related configuration data*/ 
    ACXTAGID_TR_CD = 2581,          /* Root tag for TR_CD element*/ 
    ACXTAGID_TRCEX = 2582,          /* Root tag for TRCEX element*/ 
    ACXTAGID_SIGNALDATA = 2583,          /* Root tag for SignalData element*/ 
    ACXTAGID_UPLOAD = 2584,          /* Root tag for Upload element*/ 
    ACXTAGID_DOWNLOAD = 2585,          /* Root tag for Download element*/ 
    ACXTAGID_MODBUS = 2600,          /* Root tag for files describing MODBUS registers*/ 
    ACXTAGID_SYS = 3072,          /* Profibus-System*/ 
    ACXTAGID_AVAILABLE = 3073,          /* Profibus vorhanden*/ 
    ACXTAGID_DP = 3074,          /* DP-Master*/ 
    ACXTAGID_VERSIONHOST = 3075,          /* Versionsnummer der Host-Software*/ 
    ACXTAGID_VERSIONDPM = 3076,          /* Versionsnummer der DP-M-Software*/ 
    ACXTAGID_VERSIONDPR = 3077,          /* Versionsnummer der DP-R-Software*/ 
    ACXTAGID_VERSIONDPREX = 3078,          /* Versionsnummer DP-R aus DPR_SS_VERSION*/ 
    ACXTAGID_BUS = 3079,          /* Bus*/ 
    ACXTAGID_BAUDRATE = 3080,          /* Baudrate am DP-Bus*/ 
    ACXTAGID_CYCLETIME = 3081,          /* Zykluszeit fuer die Abfrage aller Slaves*/ 
    ACXTAGID_DATAEXTIME = 3082,          /* Data Exchange Zeit in [s,s,userdef]*/ 
    ACXTAGID_MASTER = 3083,          /* Compound-Tag fuer Profibus-Master*/ 
    ACXTAGID_SLAVE = 3084,          /* Compound-Tag fuer Slave-Daten*/ 
    ACXTAGID_IDENTNO = 3085,          /* Ident-Nummer des Slaves*/ 
    ACXTAGID_IDENTNOEX = 3086,          /* Ident-Nummer des Slaves*/ 
    ACXTAGID_ISOCHRONMODESUPPORT = 3087,          /* Slave fuer isochronen Betrieb am Profibus projektiert*/ 
    ACXTAGID_DATAEXCHANGETIME = 3088,          /* Zeitpunkt fuer das Ende der zyklischen Datenuebertragung*/ 
    ACXTAGID_INPUTTIME = 3089,          /* Zeitpunkt fuer Istwerterfassung*/ 
    ACXTAGID_MASTERAPPCYCTIME = 3090,          /* Lagereglertakt*/ 
    ACXTAGID_OUTPUTTIME = 3091,          /* Zeitpunkt fuer Sollwertuebernahme*/ 
    ACXTAGID_PROFIBUSCYCLETIME = 3092,          /* Profibus Zykluszeit*/ 
    ACXTAGID_SLOT = 3093,          /* Header fuer Slot-Daten*/ 
    ACXTAGID_CLIENTNR = 3094,          /* ClientIndex fuer den Zugriff auf die Client-Assign-Tabelle*/ 
    ACXTAGID_IOTYPE = 3095,          /* E/A-Kennung*/ 
    ACXTAGID_LOGBASEADDR = 3096,          /* logische Basisadresse des Slots*/ 
    ACXTAGID_MACHAXISNR = 3097,          /* Maschinenachse*/ 
    ACXTAGID_AXIS = 3098,          /* Header fuer Achsdaten*/ 
    ACXTAGID_ENCODER1 = 3099,          /* Achsindex Geber 1*/ 
    ACXTAGID_ENCODER2 = 3100,          /* Achsindex Geber 2*/ 
    ACXTAGID_CLIENT = 3101,          /* Header fuer Clientdaten*/ 
    ACXTAGID_SLOTNRS = 3102,          /* Header fuer Slotnummernarray*/ 
    ACXTAGID_SLOTNR = 3103,          /* Slotnummer des DriveObjects*/ 
    ACXTAGID_BUSNRS = 3104,          /* Header fuer Busnummernarray*/ 
    ACXTAGID_BUSNR = 3105,          /* Busnummer*/ 
    ACXTAGID_NR = 3106,          /* Slotnummer (dpSlotCfgSlotNr)*/ 
    ACXTAGID_ID = 3107,          /* DriveObjekt-Identnummer*/ 
    ACXTAGID_DO = 3108,          /* Header fuer DriveObjekt*/ 
    ACXTAGID_TYPEID = 3109,          /* DriveObjekt-Typ*/ 
    ACXTAGID_BUSADDR = 3110,          /* Busadresse*/ 
    ACXTAGID_BASETYPE = 3111,          /* DO-Basis Objekttyp fuer Numerik Token Zugriff*/ 
    ACXTAGID_ACXNAME = 3112,          /* Dateiname des ACX fuer die Beschreibung der Parameter des DO Typs*/ 
    ACXTAGID_BUSADDROFCULINKMASTER = 3113,          /* Adresse der CU am Profibus*/ 
    ACXTAGID_DOUNIT = 3114,          /* Einheit im Numeriktoken ( 1 - 31 )*/ 
    ACXTAGID_DPMASTERSYSTEMID = 3115,          /* System-Id des DP-Master*/ 
    ACXTAGID_SUBNETID = 3116,          /* Subnet-Kennung als HEX-String*/ 
    ACXTAGID_PNNR = 3117,          /* PROFINET-Slotnummer (dpSlotCfgPNSlotNr)*/ 
    ACXTAGID_IPADDR = 3118,          /* IP Address Compound Header (CPI Profinet)*/ 
    ACXTAGID_IPADDRBYTE = 3119,          /* IP Addressdaten (CPI Profinet)*/ 
    ACXTAGID_DEVICENAME = 3120,          /* Geraetename (CPI Profinet)*/ 
    ACXTAGID_AT = 3328,          /* root element of AOP masks system texts*/ 
    ACXTAGID_AH = 3329,          /* root element of AOP masks help texts*/ 
    ACXTAGID_AOPSYSTEMTEXT = 3330,          /* an AOP system text*/ 
    ACXTAGID_AOPHELPTEXT = 3331,          /* an AOP help text*/ 
    ACXTAGID_AOPVERSION = 3332,          /* AOP version*/ 
    ACXTAGID_TEXTVERSION = 3333,          /* text structure version*/ 
    ACXTAGID_TEXTLEN = 3334,          /* text length*/ 
    ACXTAGID_TCO = 3350,          /* TCO-Parameter*/ 
    ACXTAGID_UNIQUENUMBER = 3351,          /* Seriennummer des Geraets*/ 
    ACXTAGID_RETURNEDPRODUCTCNT = 3352,          /* Rueckwarenzaehler*/ 
    ACXTAGID_CURRENTDATASET = 3353,          /* aktueller Datensatz*/ 
    ACXTAGID_OPERATIONTIME = 3354,          /* Betriebszeit im 10 Minuten Raster*/ 
    ACXTAGID_MAXTEMPEXCEEDED = 3355,          /* >Anz. Betriebstemperaturueberschreitungen*/ 
    ACXTAGID_ONOFFCOUNTER = 3356,          /* Anzahl Einschaltvorgaenge*/ 
    ACXTAGID_KEYCOUNTER = 3357,          /* */ 
    ACXTAGID_HOSTPARAMETER = 3358,          /* Hostparameter des Geraets*/ 
    ACXTAGID_CFWRITECOUNT = 3359,          /* */ 
    ACXTAGID_CFDATA = 3360,          /* */ 
    ACXTAGID_MRU = 3361,          /* */ 
    ACXTAGID_DATA = 3362,          /* Datenteil*/ 
    ACXTAGID_TEMPLOW = 3363,          /* Betriebstemperatur min.*/ 
    ACXTAGID_TEMPHIGH = 3364,          /* Betriebstemperatur max.*/ 
    ACXTAGID_TEMPCRITICAL = 3365,          /* kritische Grenztemperatur*/ 
    ACXTAGID_TEMPLOWEXCEEDED = 3366,          /* Anz. Betriebstemperaturunterschreitungen*/ 
    ACXTAGID_TEMPHIGHEXCEEDED = 3367,          /* Anz. Betriebstemperaturueberschreitungen*/ 
    ACXTAGID_TEMPCRITICALEXCEEDED = 3368,          /* Anz. kritische Grenztemperaturueberschr.*/ 
    ACXTAGID_D01_OVERLOAD = 3369,          /* Anz. Ueberlast der Ausgangstreiber DO Byte 0/1*/ 
    ACXTAGID_D23_OVERLOAD = 3370,          /* Anz. Ueberlast der Ausgangstreiber DO Byte 2/3*/ 
    ACXTAGID_D45_OVERLOAD = 3371,          /* Anz. Ueberlast der Ausgangstreiber DO Byte 4/5*/ 
    ACXTAGID_A0_OVERTEMP = 3372,          /* Anz. Temperaturueberschr. Analagmodul 0*/ 
    ACXTAGID_A0_OVERLOAD = 3373,          /* Anz. Ausgangueberlastung Analagmodul 0*/ 
    ACXTAGID_A0_LIMITEXCEEDED = 3374,          /* Anz. Eingangsgrenzwertueberschr. Analagmodul 0*/ 
    ACXTAGID_A1_OVERTEMP = 3375,          /* Anz. Temperaturueberschr. Analagmodul 1*/ 
    ACXTAGID_A1_OVERLOAD = 3376,          /* Anz. Ausgangueberlastung Analagmodul 1*/ 
    ACXTAGID_A1_LIMITEXCEEDED = 3377,          /* Anz. Eingangsgrenzwertueberschr. Analagmodul 1*/ 
    ACXTAGID_PRODUCTIONCOMMENT = 3378,          /* Fuer Fertigung reservierter Bereich*/ 
    ACXTAGID_MAXCPUTEMP = 3379,          /* maximal  gemessene CPU-Temperatur, in Grad*/ 
    ACXTAGID_CPUTHROTTLEEVENTS = 3380,          /* Zaehler fuer Intervalle mit Throttling-Ereignissen*/ 
    ACXTAGID_ECC_CORR_NVRAM = 3381,          /* Zaehler fuer korrigierte Fehler im NVRAM*/ 
    ACXTAGID_ECC_FAIL_NVRAM = 3382,          /* Zaehler fuer unkorrigierbare Fehler im NVRAM*/ 
    ACXTAGID_ECC_CORR_DRAM = 3383,          /* Zaehler fuer korrigierte Fehler im DRAM*/ 
    ACXTAGID_ECC_FAIL_DRAM = 3384,          /* Zaehler fuer unkorrigierte Fehler im DRAM*/ 
    ACXTAGID_VOLTAGE_MIN = 3385,          /* minimal gemessene Versorgungsspannung, in mV*/ 
    ACXTAGID_VOLTAGE_MAX = 3386,          /* maximal gemessene Versorgungsspannung, in mV*/ 
    ACXTAGID_IOERRORS = 3387,          /* Zaehler fuer I/O-Fehler auf dieser CF-Karte*/ 
    ACXTAGID_FSERRORS = 3388,          /* Zaehler fuer "schlimme" Filesystemfehler auf CF */ 
    ACXTAGID_MAXCPUTEMPNEW = 3389,          /* maximal gemessene CPU-Temperatur, in Grad mit groesserem Wertebereich*/ 
    ACXTAGID_THROTTLEEVENTS = 3390,          /* neuer Zaehler fuer die Intervalle mit Throttling-Ereignissen*/ 
    ACXTAGID_SSDWRITECOUNT = 3391,          /* Zaehler fuer die Zugriffe auf die CF-Karte*/ 
    ACXTAGID_PDMERGEDEF = 7700,          /* PDMergeDef*/ 
    ACXTAGID_PDMERGE = 7701,          /* PDMerge*/ 
    ACXTAGID_PDFILTER = 7702,          /* PDFilter*/ 
    ACXTAGID_DOVIEWNR = 7703,          /* DOViewNr*/ 
    ACXTAGID_DOCLASSNR = 7704,          /* DOClassNr*/ 
    ACXTAGID_FWVERSION = 7705,          /* FWVersion*/ 
    ACXTAGID_PDFILTERINDEX = 7706,          /* PDFilterIndex*/ 
    ACXTAGID_PDFILTERMASK = 7707,          /* PDFilterMask*/ 
    ACXTAGID_EXISTSINPDFILTER = 7708,          /* ExistsInPDFilter*/ 
    ACXTAGID_PDFILTERVALUE = 7709          /* PDFilterValue*/ 
};


enum Acx_DataType
{
    ACX_DATATYPE_UNKNOWN = -1,          /* unknown data type*/ 
    ACX_DATATYPE_BOOL = 0,          /* 1 byte; false==0, true !=0*/ 
    ACX_DATATYPE_INT8 = 1,          /* signed 1 byte*/ 
    ACX_DATATYPE_INT16 = 2,          /* signed 2 byte*/ 
    ACX_DATATYPE_INT32 = 3,          /* signed 4 byte*/ 
    ACX_DATATYPE_INT64 = 4,          /* signed 8 byte*/ 
    ACX_DATATYPE_UINT8 = 5,          /* unsigned 1 byte*/ 
    ACX_DATATYPE_UINT16 = 6,          /* unsigned 2 byte*/ 
    ACX_DATATYPE_UINT32 = 7,          /* unsigned 4 byte*/ 
    ACX_DATATYPE_UINT64 = 8,          /* unsigned 8 byte*/ 
    ACX_DATATYPE_FLOAT32 = 9,          /* float 4 byte*/ 
    ACX_DATATYPE_FLOAT64 = 10,          /* double 8 byte*/ 
    ACX_DATATYPE_DATETIME = 11,          /* 8 byte BCD coded date and time; format: mm dd yy HH MM SS MS DOW state*/ 
    ACX_DATATYPE_STRING = 12,          /* ASCII string*/ 
    ACX_DATATYPE_FRAME = 13,          /* SIMUMERIK Frame-Type*/ 
    ACX_DATATYPE_AXIS = 14,          /* SIMUMERIK Axis-Type*/ 
    ACX_DATATYPE_BINARY = 15          /* Binary data*/ 
};


enum Acx_DisplayType
{
    ACX_DISPLAYTYPE_UNKNOWN = -1,          /* unknown display type*/ 
    ACX_DISPLAYTYPE_DEFAULT = 0,          /* */ 
    ACX_DISPLAYTYPE_DECIMAL = 1,          /* */ 
    ACX_DISPLAYTYPE_HEX = 2,          /* */ 
    ACX_DISPLAYTYPE_BINARY = 3,          /* */ 
    ACX_DISPLAYTYPE_ASCII = 4,          /* */ 
    ACX_DISPLAYTYPE_BICO = 5,          /* */ 
    ACX_DISPLAYTYPE_ASTERISK = 6,          /* values will be viewed as "*****"; e.g. for password parameters*/ 
    ACX_DISPLAYTYPE_SCIENTIFIC = 7,          /* can be used to display the exponential representation of a float value*/ 
    ACX_DISPLAYTYPE_RESTRICTEDASCII = 8,          /* Zeichensatzeinschraenkung fuer Archivnamen*/ 
    ACX_DISPLAYTYPE_UTF16 = 9          /* */ 
};


enum Acx_MemoryType
{
    ACX_MEMORYTYPE_STATIC = 0,          /* using static memory (SRMA)*/ 
    ACX_MEMORYTYPE_DYNAMIC = 1,          /* using dynamic memory (DRAM)*/ 
    ACX_MEMORYTYPE_NONE = 2          /* memory invariant*/ 
};


enum Acx_Unit
{
    ACX_UNIT_UNKNOWN = -1,          /* unknown unit type*/ 
    ACX_UNIT_NONE = 0,          /* {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_POSITION = 1,          /* Linear  oder Winkel Position, abhaengig vom Achstyp ( MD: Linear/Rundachse ) {SINUMERIK}*/ 
    ACX_UNIT_POSITION_LIN = 2,          /* Linear Position [ mm ; inch ; userdef ] {SINUMERIK}*/ 
    ACX_UNIT_POSITION_ROT = 3,          /* Winkel Position [ Grad ; Grad ; userdef ] {SINUMERIK}*/ 
    ACX_UNIT_SPEED = 4,          /* Linear  oder Winkel Geschwindigkeit, abhaengig vom Achstyp {SINUMERIK}*/ 
    ACX_UNIT_SPEED_LIN = 5,          /* Linear Geschw. [ mm/min ; inch/min ; userdef ] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_ROT = 6,          /* Winkel Geschw. [ U/min ; U/min ; userdef ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_ACCELERATION = 7,          /* Linear  oder Winkel Beschleunigung, abhaengig vom Achstyp {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_ACCELERATION_LIN = 8,          /* Linear Beschl. [ m/s**  ; inch/s** ; userdef ] {SINUMERIK}*/ 
    ACX_UNIT_ACCELERATION_ROT = 9,          /* Winkel Beschl. [ U/s** ; U/s** ; userdef ] {SINUMERIK}*/ 
    ACX_UNIT_JERK = 10,          /* Linear  oder Winkel Ruck, abh. vom Achstyp {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_JERK_LIN = 11,          /* Linear Ruck [ m/s*** ; inch/s*** ; userdef ] {SINUMERIK}*/ 
    ACX_UNIT_JERK_ROT = 12,          /* Winkel Ruck [ U/s 3 ; U/s 3 ; userdef ] {SINUMERIK}*/ 
    ACX_UNIT_TIME = 13,          /* Zeit [ s ; s ; userdef ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_KV = 14,          /* Lageregler Verstaerkung [ 16.667/s ; 16.667/s ; userdef ] resp. [ 1000/min ] {SINUMERIK}*/ 
    ACX_UNIT_REVOLUTION_FEED = 15,          /* Umdrehungsvorschub [ mm/Umdr ; inch/Umdr; userdef] {SINUMERIK}*/ 
    ACX_UNIT_COMPENSATION_CORR = 16,          /* Einheit fuer Temperaturkompensationswerte, abhaengig vom Achstyp {SINUMERIK}*/ 
    ACX_UNIT_FORCE = 18,          /* Kraft [N] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_MASS = 19,          /* Masse [ kg ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_INERTIA = 20,          /* Traegheitmoment [ kgm2 ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_PERCENT = 21,          /* Prozent (Zahlenwert ) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_FREQUENCY = 22,          /* Frequenz [ Hz ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_VOLTAGE_AC_PP = 23,          /* Spannung [ V ] (Spitzenwert - Spitze-Spitze) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_CURRENT_AC_PP = 24,          /* Strom [ A ] (Spitzenwert - Spitze-Spitze) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_TEMPERATURE = 25,          /* Temperatur [ Grad Celsius ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_ANGLE = 26,          /* Winkel [ Grad ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_POSITION_MIXED = 28,          /* Linear  oder Winkel Position, abhaengig vom Achstyp (MD:Linear/Rundachse). Nur fuer globale Positionen. Da hier der Achstyp noch nicht feststeht wird  mm|Grad  bzw.  inch|Grad  angezeigt.  {SINUMERIK}
-  Wenn MD10260 $MN_CONVERT_SCALING_SYSTEM = 0 ist, dann entspricht die Einheiten Linearposition der im MD10240 $MN_SCALING_IS_METRIC angegebenen Einstellung (inch oder metrisch)
-  Wenn MD10260 $MN_CONVERT_SCALING_SYSTEM = 1 ist, dann entspricht die Einheiten Linearposition der im MD10270 $MN_POS_TAB_SCALING_SYSTEM angegebenen Einstellung (1 = inch oder 0 = metrisch)*/ 
    ACX_UNIT_SPEED_LIN_P3 = 29,          /* Linear Geschw. [ m/min ; ft/min ; userdef ] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_LIN_P3_SEC = 30,          /* Linear Geschw. [ m/s ; ft/s ; userdef ] {SINUMERIK}*/ 
    ACX_UNIT_RESISTANCE = 31,          /* Widerstand [ Ohm ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_INDUCTANCE_M3 = 32,          /* Induktivitaet [ mH ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_TORQUE = 33,          /* Drehmoment [ Nm ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_TORQUE_PER_CURR = 34,          /* Drehmomentkonstante [ Nm/A ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_GAIN_CURRENT_CTRL = 35,          /* Stromreglerverstaerkung [ V/A ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_GAIN_SPEED_CTRL = 36,          /* Drehzahlreglerverstaerkung [ (Nm s)/rad ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_TIME_DRIVE_BASE_CYCLE = 38,          /* Zeit [ 31.25 us ] {SINUMERIK}*/ 
    ACX_UNIT_TIME_M6 = 39,          /* Zeit [ us ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_TIME_M3 = 40,          /* Zeit [ ms ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_POWER_P3 = 42,          /* Leistung [ kW ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_CURRENT_AC_PP_M6 = 43,          /* Strom klein (Spitzenwert - Spitze-Spitze) [ uA ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_FLUX = 44,          /* magnetic flux [ V * s ] or [ Wb ] {SINUMERIK}*/ 
    ACX_UNIT_FLUX_M6 = 45,          /* magnetic flux [ uV * s ] or [ uWb ] {SINUMERIK}*/ 
    ACX_UNIT_TORQUE_M6 = 46,          /* Drehmoment klein [ uN * m ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_GAIN_FLUX_CTRL = 47,          /*  flux control gain [ A / ( V * s ) ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_PERCENT_M1 = 48,          /* Promille (Zahlenwert 0 1000) {SINUMERIK}*/ 
    ACX_UNIT_FREQUENCY_PER_SEC = 49,          /*  [ Hz/s ] {SINUMERIK}*/ 
    ACX_UNIT_POSITION_M3 = 53,          /* Position [um] (Lineara.) o. [mGrad] (Runda.) {SINUMERIK}*/ 
    ACX_UNIT_POSITION_LIN_M3 = 54,          /* Position o. Laenge [um] M3 bezieht sich auf [mm] {SINUMERIK}*/ 
    ACX_UNIT_POSITION_ROT_M3 = 55,          /* Position o. Winkel [mGrad] {SINUMERIK}*/ 
    ACX_UNIT_POSITION_LIN_M6 = 59,          /* Position o. Laenge [nm] M6 bezieht sich auf [mm] {SINUMERIK}*/ 
    ACX_UNIT_FORCE_PER_CURR = 61,          /* Kraftkonstante [N/Aeff] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_FLUX_PER_METER = 62,          /* Spannungskonstante [Veff s/m] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_GAIN_SPEED_CTRL_LIN = 63,          /* Drehzahlreglerverstaerkung Linearmotor [Ns/m] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_FORCE_M6 = 64,          /* Kraft [uN] {SINUMERIK}*/ 
    ACX_UNIT_FLOW = 65,          /* Durchfluss [l/min] {SINUMERIK}*/ 
    ACX_UNIT_PRESSURE_BAR = 66,          /* Druck [bar] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_VOLUME_CCM = 67,          /* Volumen [ccm] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_LIN_PER_VOLTAGE = 68,          /* Streckenverstaerkung [mm/Vmin] {SINUMERIK}*/ 
    ACX_UNIT_FORCE_PER_VOLTAGE = 69,          /* Streckenverstaerkung Kraftregler[N/V] {SINUMERIK}*/ 
    ACX_UNIT_VOLTAGE_AC_PP_M3 = 80,          /* Spannung klein [mV] (Spitzenwert - Spitze-Spitze) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_VOLTAGE_AC_EFF = 81,          /* Spannung [V] (Effektivwert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_VOLTAGE_AC_EFF_M3 = 82,          /* Spannung klein [mV] (Effektivwert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_CURRENT_AC_EFF = 83,          /* Strom [A] (Effektivwert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_CURRENT_AC_EFF_M6 = 84,          /* Strom klein [uA] (Effektivwert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_REVOLUTION_FEED_M3 = 85,          /*  Umdrehungsvorschub klein [um/Umdr ; inch/10000Umdr] {SINUMERIK}*/ 
    ACX_UNIT_TIME_M1 = 90,          /* time [0.1s] {SINUMERIK}*/ 
    ACX_UNIT_TIME_M2 = 91,          /* time [10ms] {SINUMERIK}*/ 
    ACX_UNIT_TIME_M5 = 92,          /* time [0.01ms] {SINUMERIK}*/ 
    ACX_UNIT_PULSE = 93,          /* length [Pulse] {SINUMERIK}*/ 
    ACX_UNIT_PULSE_256P = 94,          /* length [256 Pulse] {SINUMERIK}*/ 
    ACX_UNIT_PULSE_M1 = 95,          /* length [0.1 Pulse] {SINUMERIK}*/ 
    ACX_UNIT_REVOLUTION = 96,          /* length revolution [U] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_ROT_P2 = 97,          /* velocity [100 U/min] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_ROT_P1 = 98,          /* velocity [10 U/min] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_ROT_M1 = 99,          /* velocity [0.1 U/min] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_ROT_M3 = 100,          /* velocity [0.001 U/min] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_PPS = 101,          /* velocity [Pulse/s] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_PPS_P2 = 102,          /* velocity [100 Pulse/s] {SINUMERIK}*/ 
    ACX_UNIT_ACCELERATION_ROT_P1_PER_MIN = 103,          /* acceleration [10 U/min/s] {SINUMERIK}*/ 
    ACX_UNIT_ACCELERATION_PPS_P4 = 104,          /* acceleration [10000 Pulse/s 2 ] {SINUMERIK}*/ 
    ACX_UNIT_FREQUENCY_M1 = 105,          /* frequency [0.1 Hz] {SINUMERIK}*/ 
    ACX_UNIT_FREQUENCY_M2 = 106,          /* frequency [0.01 Hz] {SINUMERIK}*/ 
    ACX_UNIT_GAIN_POSITION_CTRL_M1 = 107,          /* gain [0.1/s] {SINUMERIK}*/ 
    ACX_UNIT_MULTIPLE_M1 = 108,          /* multiple [0.1] {SINUMERIK}*/ 
    ACX_UNIT_MULTIPLE_M2 = 109,          /* multiple [0.01] {SINUMERIK}*/ 
    ACX_UNIT_MULTIPLE_M3 = 110,          /* multiple [0.001] {SINUMERIK}*/ 
    ACX_UNIT_MULTIPLE_M4 = 111,          /* multiple [0.0001] {SINUMERIK}*/ 
    ACX_UNIT_VOLTAGE_AC_PP_M1 = 112,          /* voltage [0.1V] (Spitzenwert - Spitze-Spitze) {SINUMERIK}*/ 
    ACX_UNIT_VOLTAGE_AC_PP_M2 = 113,          /* voltage [0.01V] (Spitzenwert - Spitze-Spitze) {SINUMERIK}*/ 
    ACX_UNIT_CURRENT_AC_PP_M1 = 114,          /* current (Spitzenwert - Spitze-Spitze) [0.1A] {SINUMERIK}*/ 
    ACX_UNIT_POWER = 115,          /* power/wattage [W] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_POWER_P2 = 116,          /* power/wattage [0.1kW] {SINUMERIK}*/ 
    ACX_UNIT_POWER_P1 = 117,          /* power/wattage [10W] {SINUMERIK}*/ 
    ACX_UNIT_PERCENT_M2 = 118,          /* percentage [0.01%] {SINUMERIK}*/ 
    ACX_UNIT_JERK_NORM = 119,          /* others [1/s 3 ] {SINUMERIK}*/ 
    ACX_UNIT_PERCENT_M2_PER_MS = 120,          /* others [0.01%/ms] {SINUMERIK}*/ 
    ACX_UNIT_PULSE_PER_REVOLUTION = 121,          /*  others [Pulse/U]] {SINUMERIK}*/ 
    ACX_UNIT_CAPACITY_M6 = 122,          /* others [uF] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_RESISTANCE_M3 = 123,          /* others [ mOhm ] {SINUMERIK}*/ 
    ACX_UNIT_TORQUE_M2 = 124,          /* others [0.01 Nm] {SINUMERIK}*/ 
    ACX_UNIT_INERTIA_M6 = 125,          /* others [Kg mm 2] {SINUMERIK}*/ 
    ACX_UNIT_GAIN_SPEED_CTRL_INV = 126,          /* Ausgleichsregler Verstaerkung [rad/(s* Nm)] {SINUMERIK}*/ 
    ACX_UNIT_INDUCTANCE = 127,          /* Induktivitaet [ H ] {SINUMERIK}*/ 
    ACX_UNIT_TEMPERATURE_K = 128,          /* Temperatur [ Kelvin ] {SINAMICS}*/ 
    ACX_UNIT_TIME_H = 129,          /* time [ h ] {SINAMICS}*/ 
    ACX_UNIT_FREQUENCY_P3 = 130,          /* frequency [ kHz ] {SINAMICS}*/ 
    ACX_UNIT_CURRENT_AC_PP_M3 = 131,          /* current (Spitzenwert - Spitze-Spitze) [ mA ] {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_CAPACITY_M3 = 132,          /* capacity [ mF ] {SINAMICS}*/ 
    ACX_UNIT_LENGTH = 133,          /* length [ m ] {SINAMICS}*/ 
    ACX_UNIT_ENERGY_KWH = 135,          /* energy [ kWh ] {SINAMICS}*/ 
    ACX_UNIT_FLUX_RELATIVE = 136,          /* magnetic flux [ % ] {SINAMICS}*/ 
    ACX_UNIT_GAIN_VOLTAGE_CTRL = 137,          /* voltage control gain [ A/V ] {SINAMICS}*/ 
    ACX_UNIT_VOLTAGE_DC = 138,          /* voltage [V] (Gleichspannungswert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_VOLTAGE_DC_M3 = 139,          /* voltage [mV] (Gleichspannungswert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_VOLTAGE_DC_M6 = 140,          /* voltage [uV] (Gleichspannungswert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_CURRENT_DC = 141,          /* current [A] (Gleichstromwert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_CURRENT_DC_M3 = 142,          /* current [mA] (Gleichstromwert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_CURRENT_DC_M6 = 143,          /* current [uA] (Gleichstromwert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_CURRENT_AC_EFF_M3 = 144,          /* Strom klein [mA] (Effektivwert) {SINUMERIK/SINAMICS}*/ 
    ACX_UNIT_LENGTH_M3 = 145,          /* length [ mm ] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_M9 = 146,          /* length [ nm ] {SINAMICS}*/ 
    ACX_UNIT_ENERGY_J = 147,          /* energy [ J ] {SINAMICS}*/ 
    ACX_UNIT_ACCELERATION_LIN_METRIC = 148,          /* metric linear acceleration [m/s**] {SINAMICS}*/ 
    ACX_UNIT_JERK_LIN_METRIC = 149,          /* metric linear jerk [m/s***] {SINAMICS}*/ 
    ACX_UNIT_SPEED_LIN_METRIC = 150,          /* metric linear velocity [mm/min] {SINAMICS}*/ 
    ACX_UNIT_SPEED_LIN_METRIC_P3 = 151,          /* metric linear velocity [m/min] {SINAMICS}*/ 
    ACX_UNIT_PRESSURE_PA = 152,          /* pressure [Pa] {SINAMICS}*/ 
    ACX_UNIT_PRESSURE_PA_PER_SEC = 153,          /* Differenzdruckaenderung [Pa/s] {SINAMICS}*/ 
    ACX_UNIT_CONDUCTANCE_PER_METER_M4 = 154,          /* Leitfaehigkeit [uS/cm] {SINAMICS}*/ 
    ACX_UNIT_THREAD_PITCH = 155,          /* Gewindesteigung [ mm/Umdr ; inch/Umdr; userdef] {SINUMERIK}*/ 
    ACX_UNIT_THREAD_PITCH_INCREMENT = 156,          /* Gewindesteigungsaenderung [ mm/Umdr/Umdr ; inch/Umdr/Umdr; userdef] {SINUMERIK}*/ 
    ACX_UNIT_SPEED_LIN_FT_PER_MIN = 157,          /* linear velocity US [ft/min = 0,3048 m/min] {SINAMICS}*/ 
    ACX_UNIT_TORQUE_LBF_FT = 158,          /* torque US [lbf ft = 4,45 N * 0,3048 m] {SINAMICS}*/ 
    ACX_UNIT_FORCE_LBF = 159,          /* force US (poundforce) [lbf = 4,45 N] {SINAMICS}*/ 
    ACX_UNIT_POWER_HP = 160,          /* horse power (US) [HP = (rnd) 0,74569987 kW] {SINAMICS}*/ 
    ACX_UNIT_GAIN_SPEED_CTRL_LBF_FT_SEC_PER_RAD = 161,          /* Drehzahlreglerverstaerkung US [lbf*ft*s/rad = 1,35636 Nms/rad] {SINAMICS}*/ 
    ACX_UNIT_TEMPERATURE_F = 162,          /* temperature US (Fahrenheit) [F = C*9/5 + 32 F; 1 F = 5/9 K] {SINAMICS}*/ 
    ACX_UNIT_ACCELERATION_LIN_FT_PER_SQR_SEC = 163,          /* acceleration US [ft/s^2 = 0,3048 m/s^2] {SINAMICS}*/ 
    ACX_UNIT_FLUX_PER_FT = 164,          /* Spannungskonstante US [Veff s/ft = Veff s/0,3048m] {SINAMICS}*/ 
    ACX_UNIT_GAIN_SPEED_CTRL_LIN_LBF_SEC_PER_FT = 165,          /* Drehzahlreglerverstaerkung Linearmotor US [lbf*s/ft = 4,45 Ns/0,3048 m] {SINAMICS}*/ 
    ACX_UNIT_INERTIA_LB_SQR_FT = 166,          /* Traegheitmoment US [lb ft^2 = 0,45359 kg / (0,3048 m)^2] {SINAMICS}*/ 
    ACX_UNIT_JERK_LIN_FT_PER_CUBIC_SEC = 167,          /* jerk linear US [ft/s^3 = 0,3048 m/s^3] {SINAMICS}*/ 
    ACX_UNIT_MASS_LB = 168,          /* mass US (pound) [lb = 0,45359 kg] {SINAMICS}*/ 
    ACX_UNIT_TORQUE_LBF_FT_PER_A = 169,          /* Drehmomentkonstante US [lbf*ft/A = 0,3048m*4,45N/A] {SINAMICS}*/ 
    ACX_UNIT_FORCE_LBF_PER_A = 170,          /* Kraftkonstante US [lbf/Aeff = 4,45 N/Aeff] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_FT = 171,          /* length US (foot) [ft = 0,3048 m] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_INCH = 172,          /* length US (inch) [inch = 25,400 mm] {SINAMICS}*/ 
    ACX_UNIT_UNIT_SYSTEM_SI = 173,          /* unit system SI; affects the actual unit of the parameter {SINAMICS}*/ 
    ACX_UNIT_UNIT_SYSTEM_SI_REL = 174,          /* unit system SI/%; affects the actual unit of the parameter {SINAMICS}*/ 
    ACX_UNIT_UNIT_SYSTEM_US = 175,          /* unit system US; affects the actual unit of the parameter {SINAMICS}*/ 
    ACX_UNIT_UNIT_SYSTEM_US_REL = 176,          /* unit system US/%; affects the actual unit of the parameter {SINAMICS}*/ 
    ACX_UNIT_GAIN_POSITION_CTRL_P3_PER_MIN = 177,          /* gain position control [1000/min] {SINAMICS}*/ 
    ACX_UNIT_ONE_REL = 178,          /* 1 relative; similar to percent [1] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_UNIT = 179,          /* general length unit; can be used for almost everything [?] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_UNIT_PER_SEC = 180,          /* speed relative to general length unit; can be used for almost everything [?/s] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_UNIT_PER_SQR_SEC = 181,          /* acceleration relative to general length unit; can be used for almost everything [?/s^2] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_UNIT_PER_CUBIC_SEC = 182,          /* jerk relative to general length unit; can be used for almost everything [?/s^3] {SINAMICS}*/ 
    ACX_UNIT_SPEED_LIN_METRIC_PER_SEC = 183,          /* speed linear [mm/s] {SINAMICS}*/ 
    ACX_UNIT_SPEED_LIN_INCH_PER_SEC = 184,          /* speed linear [inch/s] {SINAMICS}*/ 
    ACX_UNIT_SPEED_ROT_DEGREE_PER_SEC = 185,          /* speed rot [°/s] {SINAMICS}*/ 
    ACX_UNIT_ACCELERATION_LIN_METRIC_PER_SQR_SEC = 186,          /* acceleration linear [mm/s^2] {SINAMICS}*/ 
    ACX_UNIT_ACCELERATION_LIN_INCH_PER_SQR_SEC = 187,          /* acceleration linear [inch/s^2] {SINAMICS}*/ 
    ACX_UNIT_ACCELERATION_ROT_DEGREE_PER_SQR_SEC = 188,          /* acceleration rot [°/s^2] {SINAMICS}*/ 
    ACX_UNIT_JERK_LIN_METRIC_PER_CUBIC_SEC = 189,          /* jerk linear [mm/s^3] {SINAMICS}*/ 
    ACX_UNIT_JERK_LIN_INCH_PER_CUBIC_SEC = 190,          /* jerk linear [inch/s^3] {SINAMICS}*/ 
    ACX_UNIT_JERK_ROT_DEGREE_PER_CUBIC_SEC = 191,          /* jerk rot [°/s^3] {SINAMICS}*/ 
    ACX_UNIT_PRESSURE_PSI = 192,          /* pressure (US) [psi] {SINAMICS}*/ 
    ACX_UNIT_FLOW_PER_SEC = 193,          /* flow / Durchfluss [l/s] {SINAMICS}*/ 
    ACX_UNIT_FLOW_P3_PER_SEC = 194,          /* flow / Durchfluss [m^3/s] {SINAMICS}*/ 
    ACX_UNIT_FLOW_P3 = 195,          /* flow / Durchfluss [m^3/min] {SINAMICS}*/ 
    ACX_UNIT_FLOW_PER_HOUR = 196,          /* flow / Durchfluss [l/h] {SINAMICS}*/ 
    ACX_UNIT_FLOW_P3_PER_HOUR = 197,          /* flow / Durchfluss [m^3/h] {SINAMICS}*/ 
    ACX_UNIT_FLOW_GALLON_PER_SEC = 198,          /* flow / Durchfluss [gallon/s] {SINAMICS}*/ 
    ACX_UNIT_FLOW_CUBIC_INCH_PER_SEC = 199,          /* flow / Durchfluss [inch^3/s] {SINAMICS}*/ 
    ACX_UNIT_FLOW_GALLON = 200,          /* flow / Durchfluss [gallon/min] {SINAMICS}*/ 
    ACX_UNIT_FLOW_CUBIC_INCH = 201,          /* flow / Durchfluss [inch^3/min] {SINAMICS}*/ 
    ACX_UNIT_FLOW_GALLON_PER_HOUR = 202,          /* flow / Durchfluss [gallon/h] {SINAMICS}*/ 
    ACX_UNIT_FLOW_CUBIC_INCH_PER_HOUR = 203,          /* flow / Durchfluss [inch^3/h] {SINAMICS}*/ 
    ACX_UNIT_MASS_FLOW_PER_SEC = 204,          /* mass flow [kg/s] {SINAMICS}*/ 
    ACX_UNIT_MASS_FLOW = 205,          /* mass flow [kg/min] {SINAMICS}*/ 
    ACX_UNIT_MASS_FLOW_PER_HOUR = 206,          /* mass flow [kg/h] {SINAMICS}*/ 
    ACX_UNIT_MASS_FLOW_P3 = 207,          /* mass flow [t/min] {SINAMICS}*/ 
    ACX_UNIT_MASS_FLOW_P3_PER_HOUR = 208,          /* mass flow [t/h] {SINAMICS}*/ 
    ACX_UNIT_MASS_FLOW_LB_PER_SEC = 209,          /* mass flow [lb/s] {SINAMICS}*/ 
    ACX_UNIT_MASS_FLOW_LB = 210,          /* mass flow [lb/min] {SINAMICS}*/ 
    ACX_UNIT_MASS_FLOW_LB_PER_HOUR = 211,          /* mass flow [lb/h] {SINAMICS}*/ 
    ACX_UNIT_FORCE_P3 = 212,          /* force [kN] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_UNIT_P3_PER_MIN = 213,          /* speed relative to general length unit; can be used for almost everything [1000 lu/min] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_UNIT_P3_PER_SQR_SEC = 214,          /* acceleration relative to general length unit; can be used for almost everything [1000 lu/s^2] {SINAMICS}*/ 
    ACX_UNIT_LENGTH_UNIT_P3_PER_CUBIC_SEC = 215,          /* jerk relative to general length unit; can be used for almost everything [1000 lu/s^3] {SINAMICS}*/ 
    ACX_UNIT_SPEED_LIN_INCH_PER_MIN = 216,          /* speed linear [inch/min] {SINAMICS}*/ 
    ACX_UNIT_SPEED_ROT_DEGREE_PER_MIN = 217,          /* speed rot [°/min] {SINAMICS}*/ 
    ACX_UNIT_UNIT_SYSTEM_IEC_MOTOR = 218,          /* unit system IEC motor (50 Hz, SI unit); affects the actual unit of the parameter {SINAMICS}*/ 
    ACX_UNIT_UNIT_SYSTEM_NEMA_MOTOR = 219,          /* unit system NEMA motor (60 Hz, US unit); affects the actual unit of the parameter {SINAMICS}*/ 
    ACX_UNIT_UNIT_SYSTEM_PHYS = 220,          /* unit system physical (for parameters where SI equal US); affects the actual unit of the parameter {SINAMICS}*/ 
    ACX_UNIT_UNIT_SYSTEM_PHYS_REL = 221,          /* unit system relative (for parameters where SI equal US); affects the actual unit of the parameter {SINAMICS}*/ 
    ACX_UNIT_SPEED_MM_PER_TOOTH = 222,          /* linear velocity [mm/tooth] {SINUMERIK}*/ 
    ACX_UNIT_LENGTH_M6 = 223,          /* length [ um ] {SINAMICS}*/ 
    ACX_UNIT_FREQUENCY_ROT = 224,          /* Drehfrequenz [ Hz ] {SINAMICS}*/ 
    ACX_UNIT_FLUX_AC_EFF = 225,          /* magnetic flux, (Strangwert), effektiv [ Veff * s ] {SINAMICS}*/ 
    ACX_UNIT_POSITION_LIN_P3 = 226,          /* Position o. Laenge [m] P3 bezieht sich auf [mm] {SIMODRIVE}*/ 
    ACX_UNIT_PARTS_PER_MIN = 227,          /* parts per minute {SINAMICS}*/ 
    ACX_UNIT_FLOW_CUBIC_FEET_PER_SEC = 228,          /* Durchfluss (Volumen) [ft³/s] {SINAMICS}*/ 
    ACX_UNIT_FLOW_CUBIC_FEET = 229,          /* Durchfluss (Volumen) [ft³/min] {SINAMICS}*/ 
    ACX_UNIT_BTU_PER_MIN = 230,          /* Wärmeenergie (British thermal unit) pro Minute [BTU/min] {SINAMICS}*/ 
    ACX_UNIT_BTU_PER_HOUR = 231,          /* Wärmeenergie (British thermal unit) pro Stunde [BTU/h] {SINAMICS}*/ 
    ACX_UNIT_PRESSURE_BAR_M3 = 232,          /* Millibar [mbar] {SINAMICS}*/ 
    ACX_UNIT_PRESSURE_INCH_WATER_GAUGE = 233,          /* inch water gauge (1 inch of water [4 °C] = 0.249 088 908 kilopascal) [inch wg] {SINAMICS}*/ 
    ACX_UNIT_PRESSURE_FT_WATER_GAUGE = 234,          /* foot water gauge [ft wg] {SINAMICS}*/ 
    ACX_UNIT_PRESSURE_METER_WATER_GAUGE = 235,          /* meter water gauge [m wg] {SINAMICS}*/ 
    ACX_UNIT_HUMIDITY_RELATIVE = 236,          /* relative humidity (relative Luftfeuchtigkeit) [% r.h.] {SINAMICS}*/ 
    ACX_UNIT_HUMIDITY_SPECIFIC = 237,          /* airhumidity specific (spezifische Luftfeuchtigkeit) [g/kg] {SINAMICS}*/ 
    ACX_UNIT_FORCE_PER_CURR_DC = 238,          /* Kraftkonstante [N/A] (DC-Werte, nicht effektiv) {SINAMICS}*/ 
    ACX_UNIT_FLUX_PER_METER_DC = 239,          /* Spannungskonstante [Vs/m] (DC-Werte, nicht effektiv) {SINAMICS}*/ 
    ACX_UNIT_FLUX_M3 = 240,          /* magnetic flux [ mV * s ] or [ mWb ] {SINAMICS}*/ 
    ACX_UNIT_POWER_REACTIVE = 241,          /* Blindleistung [ VA ] or [var]? {SINAMICS}*/ 
    ACX_UNIT_POWER_REACTIVE_P3 = 242,          /* Blindleistung [ kVA ] or [kvar]? {SINAMICS}*/ 
    ACX_UNIT_POWER_REACTIVE_P6 = 243,          /* Blindleistung [ MVA ] or [Mvar]? {SINAMICS}*/ 
    ACX_UNIT_POWER_REACTIVE_M3 = 244,          /* Blindleistung [ mVA ] or [mvar]? {SINAMICS}*/ 
    ACX_UNIT_UNIT_SYSTEM_NEMA_SI_UNITS = 245,          /* unit system NEMA motor (60 Hz, SI unit); affects the actual unit of the parameter {SINAMICS}*/ 
    ACX_UNIT_FORCE_PER_METER_M6 = 246,          /* PID control gain factor [ F/um ] {SINAMICS}*/ 
    ACX_UNIT_TIME_MIN = 247,          /* Zeit [ minute ] {SINUMERIK}*/ 
    ACX_UNIT_POWER_PER_SPEED_ROT_M3 = 248,          /* Linear drehzahlabhängiger Verlustkoeffizient (Thermisches Motormodel) [ W min/1000 ] {SINAMICS}*/ 
    ACX_UNIT_POWER_HP_PER_SPEED_ROT_M3 = 249,          /* Linear drehzahlabhängiger Verlustkoeffizient (Thermisches Motormodel) [ HP min/1000 ] {SINAMICS}*/ 
    ACX_UNIT_POWER_PER_SQR_CURRENT = 250,          /* Quadratisch lastabhängiger Verlustkoeffizient (Thermisches Motormodel) [ W/A² ] {SINAMICS}*/ 
    ACX_UNIT_POWER_PER_SQR_SPEED_ROT_M6 = 251,          /* Quadratisch drehzahlabhängiger Verlustkoeffizient (Thermisches Motormodel) [ W min²/1000² ] {SINAMICS}*/ 
    ACX_UNIT_POWER_PER_CURRENT = 252,          /* Linear lastabhängiger Verlustkoeffizient (Thermisches Motormodel) [ W/A ] {SINAMICS}*/ 
    ACX_UNIT_POWER_HP_PER_CURRENT = 256,          /* Linear lastabhängiger Verlustkoeffizient (Thermisches Motormodel) [ HP/A ] {SINAMICS}*/ 
    ACX_UNIT_POWER_HP_PER_SQR_CURRENT = 257,          /* Quadratisch lastabhängiger Verlustkoeffizient (Thermisches Motormodel) [ HP/A² ] {SINAMICS}*/ 
    ACX_UNIT_POWER_HP_PER_SQR_SPEED_ROT_M6 = 258,          /* Quadratisch drehzahlabhängiger Verlustkoeffizient (Thermisches Motormodel) [ HP min²/1000² ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_CAPACITY_P3 = 259,          /* Thermische Kapazität (Thermisches Motormodel) [ kW sec/K ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_CAPACITY_HP = 260,          /* Thermische Kapazität (Thermisches Motormodel) [ HP sec/K ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_CONDUCTIVITY_HP = 261,          /* Thermische Leitfähigkeit (Thermisches Motormodel) [ HP/K ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_CONDUCTIVITY = 262,          /* Thermische Leitfähigkeit (Thermisches Motormodel) [ W/K ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_COND_PER_SPEED_ROT_M3 = 263,          /* Linear drehzahlabhängiger Wärmeleitwertkoeffizient (Thermisches Motormodel) [ W min/(1000 K) ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_COND_PER_SQR_SPEED_ROT_M6 = 264,          /* Quadratisch drehzahlabhängiger Wärmeleitwertkoeffizient (Thermisches Motormodel) [ W min²/(1000² K) ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_COND_HP_PER_SPEED_ROT_M3 = 265,          /* Linear drehzahlabhängiger Wärmeleitwertkoeffizient (Thermisches Motormodel) [ HP min/(1000 K) ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_COND_HP_PER_SQR_SPEED_ROT_M6 = 266,          /* Quadratisch drehzahlabhängiger Wärmeleitwertkoeffizient (Thermisches Motormodel) [ HP min²/(1000² K) ] {SINAMICS}*/ 
    ACX_UNIT_GAIN_DIFF_POS_CTRL = 267,          /* Differenzlageverstärkung (APC) [ Nm/rad ] {SINAMICS}*/ 
    ACX_UNIT_GAIN_DIFF_POS_CTRL_LBF_FT_PER_RAD = 268,          /* Differenzlageverstärkung US (APC) [ lbf*ft/rad ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_RESISTANCE = 269,          /* Thermischer Widerstand (Thermisches Motormodel) [ K/W ] {SINAMICS}*/ 
    ACX_UNIT_THERMAL_RESISTANCE_HP = 270,          /* Thermischer Widerstand (Thermisches Motormodel) [ K/HP ] {SINAMICS}*/ 
    ACX_UNIT_PARTS_PER_MILLION = 271,          /* parts per million [ ppm ] {SINAMICS}*/ 
    ACX_UNIT_SQR_TIME_SQR_SEC = 272,          /* square time [ s^2 ] {SINAMICS}*/ 
    ACX_UNIT_ENERGY_WH = 273,          /* energy [ Wh ] {SINAMICS}*/ 
    ACX_UNIT_POWER_APPARENT = 274,          /* Scheinleistung [ VA ] {SINAMICS}*/ 
    ACX_UNIT_POWER_APPARENT_P3 = 275,          /* Scheinleistung [ kVA ] {SINAMICS}*/ 
    ACX_UNIT_POWER_APPARENT_P6 = 276,          /* Scheinleistung [ MVA ] {SINAMICS}*/ 
    ACX_UNIT_ANGLE_M3 = 277,          /* Winkel [ mGrad ] {SINAMICS}*/ 
    ACX_UNIT_CONDUCTANCE = 278,          /* conductance (Leitfähigkeit) [ A/V ] {SINAMICS}*/ 
    ACX_UNIT_PRESSURE_KG_FORCE_PER_SQR_METER_M4 = 279          /* pressure unit kilogram-force per square centimeter [ kg/cm^2 ] {SINAMICS}*/ 
};


enum Acx_Refresh
{
    ACX_REFRESH_RESTART = 0,          /* PowerOn-Restart*/ 
    ACX_REFRESH_RESET = 1,          /* */ 
    ACX_REFRESH_NEWCONF = 2,          /* */ 
    ACX_REFRESH_IMMEDIATE = 3          /* */ 
};


enum Acx_LimitCheck
{
    ACX_LIMITCHECK_OFF = 0,          /* no chek*/ 
    ACX_LIMITCHECK_ON = 1,          /* check to upper an lower limit*/ 
    ACX_LIMITCHECK_PLUS = 2,          /* greater than 0*/ 
    ACX_LIMITCHECK_MIN = 3,          /* greater than lowerlimit*/ 
    ACX_LIMITCHECK_RESERVED = 4,          /* do not use*/ 
    ACX_LIMITCHECK_BITMASK = 5          /* check to */ 
};


enum Acx_AccessLevel
{
    ACX_ACCESSLEVEL_UNKNOWN = -11,          /* */ 
    ACX_ACCESSLEVEL_INVISIBLE = -1,          /* */ 
    ACX_ACCESSLEVEL_SIEMENS = 0,          /* */ 
    ACX_ACCESSLEVEL_OEMHIGH = 1,          /* */ 
    ACX_ACCESSLEVEL_OEMLOW = 2,          /* */ 
    ACX_ACCESSLEVEL_USER = 3,          /* */ 
    ACX_ACCESSLEVEL_KEYSWITCH3 = 4,          /* */ 
    ACX_ACCESSLEVEL_KEYSWITCH2 = 5,          /* */ 
    ACX_ACCESSLEVEL_KEYSWITCH1 = 6,          /* */ 
    ACX_ACCESSLEVEL_KEYSWITCH0 = 7          /* */ 
};


enum Acx_DriveAccessLevel
{
    ACX_DRIVEACCESSLEVEL_UNKNOWN = -1,          /* invalid value, not allowed*/ 
    ACX_DRIVEACCESSLEVEL_NO_BOP_ACCESS = 0,          /* parameter is hidden; no read or write access*/ 
    ACX_DRIVEACCESSLEVEL_BOP_ACCESS_L1 = 1,          /* restricted access for standard user/personnel*/ 
    ACX_DRIVEACCESSLEVEL_BOP_ACCESS_L2 = 2,          /* restricted access for advanced user/personnel*/ 
    ACX_DRIVEACCESSLEVEL_BOP_ACCESS_L3 = 3,          /* access level for "experts"*/ 
    ACX_DRIVEACCESSLEVEL_BOP_ACCESS_L4 = 4,          /* access level for service personnel*/ 
    ACX_DRIVEACCESSLEVEL_BOP_ACCESS_FACTORY = 5,          /* access level for SIEMENS use only*/ 
    ACX_DRIVEACCESSLEVEL_HIDDEN_MACRO = 6,          /* access level for SIEMENS use only; parameter is writable in authorized param macros only*/ 
    ACX_DRIVEACCESSLEVEL_HIDDEN_DEFAULT = 7          /* access level for SIEMENS use only; parameter is never writable*/ 
};



#endif
