///////////////////////////////////////////////////////////////////////////////
/*! \file   slcapenum.h
 *  \author Hans Hubmann
 *  \date   01.10.2004
 *  \brief  SlCap enum definitions.
 *
 *  This file is part of the HMI Solutionline Cap Interface (Control Access Point)
 *  It is not intended for use internally within SlCap. It will be changed without
 *  notice.
 *
 *  (C) Copyright Siemens AG A&D MC 2003. All rights reserved.
 */
///////////////////////////////////////////////////////////////////////////////

// cap enum definition file

// SlCapErrorEnum definitions ======================================================================================
#ifndef SL_CAP_ERROR_ENUM_GROUPING4
#define SL_CAP_ERROR_ENUM_GROUPING4(C, N, V, T) SL_CAP_ERROR_ENUM_GROUPING(N, V, T)
#endif

#ifndef SL_CAP_ERROR_ENUM_GROUPING
#define SL_CAP_ERROR_ENUM_GROUPING(N, V, T)
#endif

SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NON_ERROR, SL_CAP_OK,                   0x00000000, "No error occured, yes-answer to a question")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NON_ERROR, SL_CAP_SUCCEED,              0x00300001, "SlCapImpl internal used secondary Ok")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NON_ERROR, SL_CAP_BUSY,                 0x00300002, "Processing is in progress")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NON_ERROR, SL_CAP_RETRY,                0x00300003, "Processing may be successful in case of an retry")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NON_ERROR, SL_CAP_NO,                   0x00300004, "No-answer to a question")
//SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CONTINUED,            0x00300005, "Work continues, waiting terminates")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NON_ERROR, SL_CAP_ERROR_NOT_SET,        0x003000ff, "Error not set")

//SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CONNECT_STATE_UNREFERENCED, 0x10, "This address is not referenced (There is no need to hold a connection).")
//SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CONNECT_STATE_BOOTING,      0x20, "Booting the shared memory between SlCap and COS/CP.")
//SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CONNECT_STATE_OPENING,      0x30, "Opening the connection (Asking for ressources).")
//SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CONNECT_STATE_CONNECTING,   0x40, "Establishing a layer-4 connection.")
//SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CONNECT_STATE_NEGOTIATING,  0x50, "Negotiating parallelism and pdu-sizes.")
//SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CONNECT_STATE_READING_CAPABILITIES, 0x60, "Exploring properties and capabilities.")
//SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CONNECT_STATE_CONNECTED,    0xa0, "A connection is established.")
//SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CONNECT_STATE_CLOSING,      0xf0, "The last reference has disappeared. The connection is closing.")

SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_UNI_ERROR, SL_CAP_NOK,                  0x80300000, "An error occurred")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_UNI_ERROR, SL_CAP_BUSY_ERROR,           0x80300001, "SlCapCBImpl/SlCapNamespace object currently in use")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ARGCOUNT_ERROR,       0x80300002, "Number of Arguments not valid")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_IN_GROUP,       0x80300003, "A grouping was not possible because of errors of other variables in this group")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_NOT_IMPLEMENTED,      0x80300004, "A part of the requested service is not (yet) implemented")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_RESOURCE_BUSY,        0x80300005, "Resource already in use (e.g. /Plc/Messages, ...)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_ADDR,       0x80300006, "The variables of a 'together'-group are located at different MPI/Profibus participants")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_TARGET,     0x80300007, "The variables of a 'together'-group are located at different targets")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_INCONSISTENT_PRIORITY_FLAGS, 0x80300008, "The variables of a 'together'-group have inconsistent priority flags")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_PROTOCOL,   0x80300009, "A variable has the SL_CAP_FLAG_FORCE_BUB_CYCLIC set, but the BUB-Cyclic protocol is not usable")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_NO_GROUPING,          0x8030000a, "Protocol does not allow grouping")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DOES_NOT_FIT_INTO_ONE_PDU, 0x8030000b, "Group does not fit into a single pdu")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_UNKNOWN_FLAG,         0x8030000c, "The modifier uFlags are undefined or illeagal")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_UNI_ERROR, SL_CAP_CLIENT_TIMEOUT,       0x8030000d, "A client specified timeout expired")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ORDER_TYPE,           0x8030000e, "The requested type of the order (e.g. read or advise) ist not available")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_UNI_ERROR, SL_CAP_CAN_NOT_CONVERT,      0x8030000f, "No data type conversion was possible")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_DATA_LOSS,            0x80300010, "Significant data precision would be lost in conversion")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_UNKNOWN_VARIABLE_NAME, 0x80300011, "Variablename not known by cap")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_PDU_FRAMING,          0x80300012, "A garbled pdu was received or type of delivered data does not correspond to expected type (nsp out of date?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_CORBA_SYSTEMEXCEPTION,0x80300013, "A CORBA exception occured")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ARGUMENT_ERROR,       0x80300014, "Argument faulty (e.g. memory fault during access)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_UNI_ERROR, SL_CAP_DIFFERENT_ERRORS,     0x80300015, "During a multiXXX call different errors occurred")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_TYPES,      0x80300016, "Writing a local variable with incompatible types")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_WRONG_ADVISE_STATE,   0x80300017, "E.g. can not unadvise because not advising")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_UNKNOWN_SERVER,       0x80300018, "Server name is not known")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DATA_SIZE,            0x80300019, "Provided data size not consistent to needed data count")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_RETRY_LATER,          0x8030001a, "A temporary ressource problem was detected")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_PATHNAME_SYNTAX,      0x8030001b, "Server pathname is not correct")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_WRONG_CAP_INSTANCE,   0x8030001c, "SlCapImpl instance not existing or not correct")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_WRONG_CB_INSTANCE,    0x8030001d, "SlCapCBImpl/SlQCapHandle not valid")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_UNKNOWN_PATH,         0x8030001e, "Pathname is not known")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_UNKNOWN_COMMAND,      0x8030001f, "Command is not known")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_CANT_OPEN_FILE,       0x80300020, "Cant open file")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_OUT_OF_HEAP,          0x80300021, "A heap allocation failed")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_FILE_WRITE_ERROR,     0x80300022, "Could not write to file")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_FILE_READ_ERROR,      0x80300023, "Could not read from file")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_TYPE_DOES_NOT_FIT_INTO_PDU, 0x80300024, "A single item does not fit into pdu")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_WRONG_CB_STATE,       0x80300025, "Wrong state of the callback object (e.g. The operation may have terminated)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_BROKEN_SERVER_CONNECTION, 0x80300026, "Server connection is broken or was broken")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_VARIABLE_INDEX,       0x80300027, "An index of a variable specification is not supported")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_TERMINATED,           0x80300028, "The referenced activity has already terminated, is missing or not yet started")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_CANCELLED,            0x80300029, "The referenced activity was cancelled")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_PIPE_EOF,             0x8030002a, "Pipe transfer reached already eof")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_PIPE_WRITE_BUSY,      0x8030002b, "Multiple writePipe calls at the same time")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_S7DOS_DLL_MISSING,    0x8030002c, "S7DOS Dll missing, S7DOS installation corrupted")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_NO_WAITABLE_ACTIVITY, 0x8030002d, "When the wait arrived at the server, there was no corresponding activity working")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_ARITY,          0x8030002e, "The multiOrder had no variables or commands")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_INCONSISTENT_MULTIORDER_FLAGS, 0x8030002f, "The variables of a multi-order have inconsistent flags (e.g. SL_CAP_FLAG_DECOUPLE, SL_CAP_FLAG_SEQUENTIALIZE_CALLBACKS, SL_CAP_FLAG_DONT_USE_REPLY_THREAD, SL_CAP_FLAG_USE_REPLY_THREAD)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_EARLY_EOF,            0x80300030, "Eof occured during set skipping")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_SKIPPING_NOT_SUPPORTED,0x80300031, "Skipping not supported on piped transfers")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_PATH_TOO_LONG,        0x80300032, "Domain path too long")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_COS_OPEN_ERROR,       0x80300033, "open_DprL4Buffer call failed (e.g. cp not running, mpi stack not started, ncu not running)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_COS_WRITE_ERROR,      0x80300034, "write_DprL4Buffer call failed")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_FILE_OP_ERROR,        0x80300035, "Error when closing a file (possibly no space on disk)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ARG_TYPE_ERROR,       0x80300036, "Argument data type not supported")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_NCKHEADER_MISSING,    0x80300037, "The uploaded file lacks the NCK-header")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_NOT_SUPPORTED,        0x80300038, "The requested funtionality or an argument is not supported")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_CLIENT_SHUTDOWN_ERROR, 0x80300039, "The SlCap client is shutting down, all pending orders are cancelled")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_INSTANCE_DISAPPEARED, 0x80300040, "The SlCap client is shutting down, all pending orders are cancelled")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_NO_ARRAY,             0x80300041, "There is no data array")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_FILE_CLOSE_ERROR,     0x80300042, "Error when closing a file (possibly no space on disk)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DATA_TYPE,            0x80300043, "The parameter datatype and data datatype is different")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_CYCLIC_DIRECTIVES_IN_GROUP, 0x80300044, "You have to decide, wheter you want cyclic reading or cyclic services within a single group. Both is not possible.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_UNEXPECTED_PDU,       0x80300045, "a unexpected response pdu was received")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_GROUPING_DIRECTIVES, 0x80300046, "contradictory uFlags detected (e.g. SL_CAP_FLAG_FORCE_DEVICE and SL_CAP_FLAG_FORCE_CACHE)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_LINEACCESS_ERROR,     0x80300047, "lineaccess incompatible with operation uFlags")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_SERVER_SHUTDOWN_ERROR, 0x80300048, "The SlCap server is shutting down, all pending orders are cancelled")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_ERROR_ILLEGAL_FLOAT,  0x80300049, "Al least one of the floatingpoint data is a NaN, is inifite or is not normalized")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ERROR_CANT_MAP_FILE_TO_MEMORY, 0x8030004a, "It was not possible to map a file into memory")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_VARIABLE_DELETED, 0x8030004b, "The advised variable was deleted.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_NONEXISTENT_MAPPING, 0x8030004c, "The referenced namespace is not mapped.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_ADDRESS_DELETED, 0x8030004e, "The referenced address was intermediately deleted.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ERROR_ACX_NO_DICT,    0x8030004f, "It was not possible to read in an acx dictionary")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_UNI_ERROR, SL_CAP_CACHE_MISS_ERROR,     0x80300050, "It was not possible to read in an acx dictionary")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_UNI_ERROR, SL_CAP_NAMESPACE_TRANSIENT_ERROR, 0x80300051, "The namespace is currently reacquiring the namespace file")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_NAMESPACE_DISAPPEARED_ERROR, 0x80300052, "The last reference to a namespace was deleted")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_DISCONNECTED,         0x80300053, "No transport connection existing")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_AMBIGUOUS,      0x80300054, "Ambiguity detected (e.g. a drive is not clearly related to a nck)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_NO_RELATED_NCK, 0x80300055, "At the machine of the drive exists no nck")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_SIGMASKS_NOT_SET,     0x80300056, "SlCap uses signals, which must be blocked in all threads under linux")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_COLLIDING_THREADING_DIRECTIVES, 0x80300057, "The flags SL_CAP_FLAG_DONT_USE_REPLY_THREAD and SL_CAP_FLAG_USE_REPLY_THREAD collide")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_CANT_DELIVER_ALL_CHANGES, 0x80300058, "There is no way to deliver all data changes, a zero update rate is not supported")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ARG_RANGE_ERROR,      0x80300059, "An argument or index exceeds the supported range")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_UNSUPPORTED_TOKEN_TYPE, 0x8030005a, "Communication protocol not supported (Token)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_REMOTELY_CANCELLED,   0x8030005b, "Protocol sequence was aborted by the remote station")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_ALONE_DIRECTIVES_IN_GROUP, 0x8030005c, "Its not possible to have variables with and without alone-flag in the same group.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_EARLY_DIRECTIVES_IN_GROUP, 0x8030005d, "Its not possible to have variables with and without early-callback-flag in the same group.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ZEROCYCLE_NOT_SUPPORTED, 0x8030005e, "A cycletime of 0 is (currently) not supported")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_UPDATE_RATE, 0x8030005f, "Grouped variables have different update rate")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_NO_CYCLIC_AVAILABLE,  0x80300060, "There is no cyclic service available.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_DECOUPLING_FLAGS, 0x80300061, "There are different decoupling flags in one order")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_SEQUENTIALIZE_FLAGS, 0x80300062, "There are different sequentialize flagsin one order")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_DIFFERENT_CALLBACK_MODE, 0x80300063, "There are different SL_CAP_FLAG_SINGLE_CALLBACK flags in one order")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_WRONG_SUBADDRESS,     0x80300064, "The subaddress specification is wrong")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_SEND_RESSOURCE_EXHAUSTED, 0x80300065, "A SCP send() call got an error")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ARG_INVALID_CACHE_KEY, 0x80300066, "The cache key contains the invalid character '^'.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ARG_INVALID_VARNAME_PREFIX, 0x80300067, "The variable name prefix contains the invalid character '^'.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_SWITCHING_MACHINE,     0x80300068, "A machine switch was activated.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ERROR_INVALID_CONN_CONFIG, 0x80300069, "Can not evaluate mmc.ini/netnames.ini, please check the corresponding files.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_MACHINE_SWITCH_LOCKED, 0x80300070, "Switching to another server/machine is locked.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_INVALID_MACHINE_SWITCH_LOCK_HANDLE, 0x80300071, "Invalid handle to unlock switching to another server/machine.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_FILE_EMPTY,            0x80300072, "Could not read from file, because file is empty (NC-Header only).")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_OMS_SZL_UNDEFINED,     0x80300073, "This SZL is not supported by PLC 1500.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_FILE_ACCESS_TIMEOUT,   0x80300074, "A file system access exceeds the maximum netDriveTimeout setting (see systemconfiguration.ini).")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_ADVISE_LIMIT_EXCEEDED, 0x80300075, "The maximum number of advised variables per sub device has been exceeded.")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_EXT_ERROR, SL_CAP_INVALID_CALL_FOR_STATE,0x80300076, "The preconditions to handle this client call are not met.")

SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_LIFESIGN_ORDER,  0x80300090, "COS/CP life sign out of order")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_UNEXPECTEDPDU,   0x80300091, "CALV internal problem (version?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_BROKEN_LINE,     0x80300092, "CALV shared memory closed")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_SHM_ERROR,       0x80300099, "Cant access the COS/CP shared memory")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_PROFILE_SYNTAX,  0x8030009a, "The sytax of a profile specification is unknown/faulty")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_TIMEOUT,         0x80300095, "Connect timeout (Control warmstart?, CP started?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_LIFESIGN_RESET,  0x8030009b, "COS/CP interupted connection by lifesign")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_LIFESIGN_TIMEOUT, 0x8030009c, "COS/CP do not react")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_DIFFERENT_VERSION, 0x8030009d, "COS/CP have different layout (different dual port RAM layout)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_DIFFERENT_MAGIC, 0x8030009e, "COS/CP have different magic (different byte order)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_CAP_CALV_UNEXPECTED,      0x8030009f, "CALV internal problem (version?)")

SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_FILE_OPEN_ERROR,  0x80300100 + 1, "Acxreader couldnt open file")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_FILE_ACCESS_ERROR, 0x80300100 + 2, "Acxreader error on file access")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, SL_CAP_ACX_OBJ_ALREADY_IN_USE, 0x80300100 + 3, "Acxreader already working (internal problem!)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, SL_CAP_ACX_NO_FILESYSTEM,    0x80300100 + 4, "Acxreader got no filesystem (internal problem!)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, SL_CAP_ACX_NO_CONTENT_HANDLER, 0x80300100 + 10, "Acxreader got no content handler (internal problem!)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_UNI_ERROR, SL_CAP_ACX_WRONG_FILE_TYPE,  0x80300100 + 11, "Acxreader got wrong file type")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_ERROR_UNKNOWN_DATATYPE, 0x80300100 + 30, "Acxreader detected unknown datatype (version problem?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_ERROR_CHECKSUM_ALGORITHM, 0x80300100 + 31, "Acxreader misses a required checksum algorithm (version problem?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, SL_CAP_ACX_ERROR_STR_WRONG_USAGE, 0x80300100 + 40, "Acxreader got unexpected call (internal problem!)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_ERROR_WRONG_LEN_UINT, 0x80300100 + 41, "Acxreader detected invalid uint length (version problem?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_ERROR_WRONG_LEN_INT, 0x80300100 + 42, "Acxreader detected invalid int length (version problem?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_ERROR_WRONG_LEN_FLOAT, 0x80300100 + 43, "Acxreader detected invalid float length (version problem?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_ERROR_TOO_MANY_ROOT_TAGS, 0x80300100 + 44, "Acxreader detected too many root tags")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, SL_CAP_ACX_ERROR_EMPTY_TAG_NOT_EMPTY, 0x80300100 + 45, "Acxreader detected an invalid emptytag")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_ERROR_MAJORVERSION_INVALID, 0x80300100 + 46, "Acxreader detected a problematic version incompatibility")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_ERROR_CHECKSUM_UNEQUAL, 0x80300100 + 47, "Acxreader detected different checksums")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_NAMESPACE_ERROR,  0x803001f8, "Acxreader detected an unknown namespace (version problem?)") 
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_ARG_ERROR, SL_CAP_ACX_NO_ROOT_TAG,      0x803001f9, "Acxreader detected no root tag (wrong file type?)") 
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_UNEXPECTED_DATATYPE, 0x803001fa, "Acxreader detected an unexpected datatype (version problem?)") 
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_SYNTAX_ERROR,     0x803001fb, "Acxreader detected a syntax error (wrong file type? version problem?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_DICT_SYNTAX_ERROR, 0x803001fc, "Acxreader detected a syntax error interpreting AcxDictionary.acx (wrong file type? version problem?)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_SYS_ERROR, SL_CAP_ACX_ACZ_CONVERSION_ERROR, 0x803001fd, "Acxreader detected an error converting ACZ to ACX")

// errors propagated throug slcapserver to clients
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_UNPLUGGED,            0x8040031a, "Cant open SCP driver, no remote station active")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_NO_HARDWARE,          0x80400310, "Cant open SCP driver, MPI/Profibus hardware not found")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_WRONG_BAUDRATE,       0x80400313, "Cant open SCP driver, wrong baudrate")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_DLL_MISSING,          0x80400320, "Cant open SCP driver, wrong baudrate")

SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_RESPONSE_NO_RESOURCES, 0x80600404, "Out of S7DOS resources")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_RESPONSE_UNKNOWN_REFERENCE, 0x80600406, "Connection was closed")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_RESPONSE_REM_ABORT,  0x8060040e, "Remote station closed connection")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_RESPONSE_LOC_TIMEOUT, 0x80600410, "Remote station not in tokenring")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_RESPONSE_CONN_REJECT, 0x80600416, "Remote station refused to connect")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_SCP_RESPONSE_NETWORK_ERROR, 0x8060041c, "Error on network interconnection")

SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_TRESPONSE_UNKNOWN_OPCODE, 0x80600801, "opcode of an OSI-Layer 4 transport request (send) is unknown")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_TRESPONSE_UNKNOWN_RECEIVER, 0x80600802, "receiver of an OSI-Layer 4 transport request (send) is unknown")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_TRESPONSE_INVALID_LENGTH, 0x80600803, "length of a OSI-Layer 4 transport request (send) is too large")

SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NCU_ERROR, SL_NCU_ACC_HARDWARE,           0x85000001, "Access error delivered from NCK/PLC/DRIVE: Hardware error")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NCU_ERROR, SL_NCU_ACC_PROTECTED,          0x85000003, "Access error delivered from NCK/PLC/DRIVE: Not allowed")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NCU_ERROR, SL_NCU_ACC_ADDRESS,            0x85000005, "Access error delivered from NCK/PLC/DRIVE: Faulty address")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NCU_ERROR, SL_NCU_ACC_DATATYPE,           0x85000006, "Access error delivered from NCK/PLC/DRIVE: Datatype not supported")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_NCU_ERROR, SL_NCU_ACC_NOT_EXISTING,        0x8500000a, "Access error delivered from NCK/PLC/DRIVE: Data do (partly) not exist")

SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_SYNTAX,        0x80600082, "Request buffer syntax error (internal problem!)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_RESOURCE,      0x80600084, "Out of COS ressources")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_REF,           0x80600085, "Connection closed")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_PARAM,         0x80600086, "COS argument error")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_SEQUENCE,      0x80600087, "Command sequence error (internal problem!)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_LOC_ABORT,     0x80600088, "Local rejection")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_REM_ABORT,     0x80600089, "Remote rejection")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_LOC_NET,       0x8060008a, "Locally detected networking error")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_REM_NET,       0x8060008b, "Remotely detected networking error")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_PROTOCOL,      0x8060008c, "Protocol error (internal problem!)")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_TIMEOUT,       0x8060008d, "Missing response")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_DEV,           0x8060008e, "Device error")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_ROUTE,         0x8060008f, "Routing error")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_OWN_ADDR,      0x80600090, "Own address faulty")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_SYS_PATH,      0x80600091, "System path error")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_LOWER_LAYER,   0x80600092, "Error detected at OSI-Layer-2 or OSI-Layer-3")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, SL_COS_RESPONSE_WITHDRAW,      0x80600093, "Withdraw occurred")

// disappear on development proceedings
//SL_CAP_ERROR_ENUM_GROUPING4(SlCapError, 0x8030ffa0, "just an error, only internally used")
//SL_CAP_ERROR_ENUM_GROUPING4(SlCapInt1, 0x8030ffa1, "internal problem in read call")
//SL_CAP_ERROR_ENUM_GROUPING4(SlCapInt2, 0x8030ffa2, "internal problem with target CBState")
//SL_CAP_ERROR_ENUM_GROUPING4(SlCapInt3, 0x8030ffa3, "not implemented Protocol")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, SlCapInt4, 0x8030ffa4, "not impl. pdu construction")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, SlCapInt5, 0x8030ffa5, "unknown VariableSubAddressType")
//SL_CAP_ERROR_ENUM_GROUPING4(SlCapInt6, 0x8030ffa6, "unknown NcuDataType")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, SlCapInt7, 0x8030ffa7, "unsupported order type for local data")
//SL_CAP_ERROR_ENUM_GROUPING4(SlCapInt8, 0x8030ffa8, "unexpected string")
//SL_CAP_ERROR_ENUM_GROUPING4(SlCapUnexpectedPdu, 0x8030ffaf, "internal exception")

//SL_CAP_ERROR_ENUM_GROUPING4(CAP_NOT_IMPL, 0x81000101, "A needed feature is not (yet) implemented")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_NO_CONNECTION, 0x81000102, "Connection is avaliable at the server")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_NO_SERVER, 0x81000103, "Wrong path to server, no server running, no local server was startable")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_RECURSION, 0x81000104, "a syncronous SlCapImpl call ist tried within another syncronous SlCapImpl call")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_MEMORY_FAULT, 0x81000105, "cap got errors accessing client provided data")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_UNEXPECTED_PDU, 0x81000106, "a unexpected response pdu was received")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_TIMEOUT, 0x81000107, "a timeout occured, waiting for the termination of a syncronous operation")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, CAP_HIDDEN_ERROR, 0x81000108, "internally used error mark")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_UNSUPPORTED_DATATYPE, 0x81000109, "datatype not supported")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_UNKNOWN_VARIABLE, 0x8100010a, "a variable with this name is not known")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_UNKNOWN_COMMAND, 0x8100010b, "unsupported command")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_WRONG_ADDRESS, 0x8100010c, "no connection can be established to this address")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_PDUFRAMING, 0x8100010e, "a received pdu was not decodable")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_ARGUMENT_COUNT, 0x81000110, "number of arguments not supported")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_ARGUMENT_TYPE, 0x81000111, "datatype of an argument not supported")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_ARGUMENT_ERROR, 0x81000112, "argument value not supported")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_TYPE_MISMATCH, 0x81000113, "cap internal type mismatch problem (needing implementation or debugging), used by val!!")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_INDEX_ERROR, 0x81000114, "at least one of the variable indexes is not supported")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_WRONG_FORMAT, 0x81000115, "the text formatting specification can not be evaluated")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_WRONG_STATE, 0x81000116, "can not be done in the current state")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_BUSY, 0x81000117, "the SlCapCBImpl structure is busy")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_INSTALLATION_CORRUPTED, 0x81000118, "dlls missing")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_SCP_SEND_RESOURCE, 0x81000119, "ressource problem at SCP-transport level")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, CAP_SCP_TIMEOUT, 0x8100011a, "timeout problem at SCP-transport level")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, CAP_SCP_RECEIVE, 0x8100011b, "cant send receives")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, CAP_SCP_SEQUENCE, 0x8100011c, "internal problem")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_CON_ERROR, CAP_KNOCK_ERROR, 0x8100011d, "error during knocking on plc's door")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_PDU_CONSISTENCY, 0x8100011e, "unexpecxted pdu data length or datatype")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_UNSUPPORTED_ERROR, 0x81000120, "only internally used used errorcode (it is an error if this occures at client level)")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_PATH_SYNTAX, 0x81000121, "a variable or command path is syntactically wrong")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_OK, 0x00000000, "no error")
//SL_CAP_ERROR_ENUM_GROUPING4(CAP_SUCCEED, 1, "success, internally used only")
SL_CAP_ERROR_ENUM_GROUPING4(SL_CAP_CATEGORY_INT_ERROR, CAP_TMPFATAL_INTERNAL, 0x81ffffff, "internally used for temprary fatal")


// SlCapQualityEnum definitions ==========================================================================
#ifndef SL_CAP_QUALITY_ENUM_GROUPING
#define SL_CAP_QUALITY_ENUM_GROUPING(N,V,T)
#endif

// STATUS_MASK Values for Quality = BAD
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_Bad, OPC_QUALITY_BAD, "The quality of the value is bad")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_ConfigError, OPC_QUALITY_CONFIG_ERROR, "The quality of the value is bad")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_NotConnected, OPC_QUALITY_NOT_CONNECTED, "The quality of the value is bad")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_DeviceFailure, OPC_QUALITY_DEVICE_FAILURE, "The quality of the value is bad")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_SensorFailure, OPC_QUALITY_SENSOR_FAILURE, "The quality of the value is bad")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_LastKnown, OPC_QUALITY_LAST_KNOWN, "The quality of the value is bad")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_CommFailure, OPC_QUALITY_COMM_FAILURE, "The quality of the value is bad")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_OutOfService, OPC_QUALITY_OUT_OF_SERVICE, "The quality of the value is bad")

// STATUS_MASK Values for Quality = UNCERTAIN
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_Uncertain, OPC_QUALITY_UNCERTAIN, "The quality of the value is uncertain")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_LastUsable, OPC_QUALITY_LAST_USABLE, "The quality of the value is uncertain")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_SensorCal, OPC_QUALITY_SENSOR_CAL, "The quality of the value is uncertain")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_EguExceeded, OPC_QUALITY_EGU_EXCEEDED, "The quality of the value is uncertain")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_SubNormal, OPC_QUALITY_SUB_NORMAL, "The quality of the value is uncertain")

// STATUS_MASK Values for Quality = GOOD
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_Good, OPC_QUALITY_GOOD, "The quality of the value is good")
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_LocalOverride, OPC_QUALITY_LOCAL_OVERRIDE, "The quality of the value is good")

// special 
SL_CAP_QUALITY_ENUM_GROUPING(SlCapQuality_NotSet, -1, "The quality of service is not set or known")


// SlCapCmdEnum definitions ==========================================================================
#ifndef SL_CAP_PI_ENUM_GROUPING
#define SL_CAP_PI_ENUM_GROUPING(N,V)
#endif

SL_CAP_PI_ENUM_GROUPING(SlCapCmd_PiStart, 1)
SL_CAP_PI_ENUM_GROUPING(SlCapCmd_PiStop, 2)
SL_CAP_PI_ENUM_GROUPING(SlCapCmd_PiResume, 3)

// SlCapL4ConStateEnum definitions ==========================================================================
#ifndef SL_CAP_CALVCONSTATE_GROUPING
#define SL_CAP_CALVCONSTATE_GROUPING(N, V, T)
#endif

SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_DISCONNECTED, 1, "Connection is inactive and disconnected" )
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_INIT, 2, "Initializing connection states and dpr")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_DPRCONNECTING, 3, "Waiting until dpr gets connected")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_DPRCONNECTED, 4, "Dpr is connected, sending an OPEN_REQ")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_OPENING, 5, "Waiting until COS/CP answers a OPEN_REQ")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_OPENED, 6, "COS/CP is opened, sending a CON_REQ")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_CONNECTING, 7, "Waiting until remote station answers a CON_REQ")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_CONNECTED, 8, "Connected to remote station, sending of the negotiating request")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_NEGOTIATING, 9, "Waiting until negotiation returns")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_NEGOTIATED, 10, "Resources are negotiated, start read of NCU-capabilities and read PLC state")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_READING_CAPABILITIES, 11, "Reading Nck Capabilities")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_WORKING, 30, "A connection is on line")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_DISCONNECT, 40, "Initiate disconnecting")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_DISCONNECTING, 41, "Wait until disconnecting completes")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_UNINIT, 42, "Free connection resources")
SL_CAP_CALVCONSTATE_GROUPING(SL_CAP_CCS_LOOPDELAYING, 100, "Delay to make less busy")

