#ifndef SLHMIVERSIONSENUM_H_INCLUDED
#define SLHMIVERSIONSENUM_H_INCLUDED

enum VersionsConfigDataFlagsEnum
{
    VERSIONS_CONFIG_DATA_FLAGS_VERSIONSINFO = 0x0001,
    VERSIONS_CONFIG_DATA_FLAGS_COMMENT = 0x0002,
    VERSIONS_CONFIG_DATA_FLAGS_IDENTITY_INFO = 0x0004,
    VERSIONS_CONFIG_DATA_FLAGS_LICENSE_INFO = 0x0008,
    VERSIONS_CONFIG_DATA_FLAGS_LOGBOOK = 0x0010,

    VERSIONS_CONFIG_DATA_COMPLETE = VERSIONS_CONFIG_DATA_FLAGS_VERSIONSINFO
                                    | VERSIONS_CONFIG_DATA_FLAGS_COMMENT
                                    | VERSIONS_CONFIG_DATA_FLAGS_IDENTITY_INFO
                                    | VERSIONS_CONFIG_DATA_FLAGS_LICENSE_INFO
                                    | VERSIONS_CONFIG_DATA_FLAGS_LOGBOOK
}
;

#endif //SLHMIVERSIONSENUM_H_INCLUDED
