/*! \file   sldcerrorint.h
 *  \author Joachim Zapf
 *  \date   25.11.2005
 *  \brief  internal error defines for common sources
 *
 *  This file is part of the HMI Solutionline Services.
 *
 *  (C) Copyright Siemens AG A&D MC 2007. All rights reserved.
*/

#if !defined(SL_DC_ERROR_INT_H)
#define SL_DC_ERROR_INT_H

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#   pragma once
#endif // ACE_LACKS_PRAGMA_ONCE

#include "sldcerror.h"

// Fehlercodes aus dc.h
#define DC_ERR_DC_DOESNT_RUN                 (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_DC_DOESNT_RUN)
#define DC_ERR_NO_CONNECTION_CONFIGURED      (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_NO_CONNECTION_CONFIGURED)
#define DC_ERR_MEM                           (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_MEM)
#define DC_ERR_PARAM                         (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_PARAM)
#define DC_ERR_OFFLINE                       (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_OFFLINE)
#define DC_ERR_DATA_REQUESTED                (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_DATA_REQUESTED)
#define DC_ERR_DATA_DOESNT_EXIST             (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_DATA_DOESNT_EXIST)
#define DC_ERR_SYSTEM_FAILURE                (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_SYSTEM_FAILURE)
#define DC_ERR_NCDDE_FAILURE                 (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_NCDDE_FAILURE)
#define DC_ERR_SYSTEM_CONFUSED               (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_SYSTEM_CONFUSED)
#define DC_ERR_TIMEOUT                       (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_TIMEOUT)
#define DC_ERR_UNKNOWN_ERROR                 (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_UNKNOWN_ERROR)
#define DC_ERR_NO_NCDDE_CONNECTION           (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_NO_NCDDE_CONNECTION)
#define DC_ERR_DC_DEADLOCK                   (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_DEADLOCK)
#define DC_ERR_DC_MMF_PTR                    (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_MMF_PTR)
#define DC_ERR_ADV_DATA_INVALID              (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_ADV_DATA_INVALID)
#define DC_ERR_DATA_INVALID                  (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_DATA_INVALID)
#define DC_ERR_ALREADY_LOGED                 (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_ALREADY_LOGED)
#define DC_ERR_GET_PROC_ADDRESS              (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_GET_PROC_ADDRESS)
#define DC_ERR_INVALID_DRV_CON_ENTRY         (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_INVALID_DRV_CON_ENTRY)
#define DC_ERR_WRITE_PROFILE_STRING          (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_WRITE_PROFILE_STRING)
#define DC_ERR_OFFLINE_DATA                  (SL_ERR_DC | SL_DC_SERVICE | SL_DC_ERR_OFFLINE_DATA)

// Fehlercodes aus StCIf.h
#define ST_CIF_ERR_GET_PROC_ADDRESS          (SL_ERR_DC | SL_SNX_TOPO | SL_ST_ERR_GET_PROC_ADDRESS)
#define ST_CIF_ERR_ASYNC_RUNNING             (SL_ERR_DC | SL_SNX_TOPO | SL_ST_ERR_ASYNC_RUNNING)
#define ST_CIF_ERR_SINAMICS                  (SL_ERR_DC | SL_SNX_TOPO | SL_ST_ERR_SINAMICS)
#define ST_CIF_ERR_NO_TOPO_TARGET            (SL_ERR_DC | SL_SNX_TOPO | SL_ST_ERR_NO_TOPO_TARGET)
#define ST_CIF_ERR_MORE_DATA                 (SL_ERR_DC | SL_SNX_TOPO | SL_ST_ERR_MORE_DATA)
#define ST_CIF_ERR_INIT_ALREADY_IN_PROGRESS  (SL_ERR_DC | SL_SNX_TOPO | SL_ST_ERR_INIT_ALREADY_IN_PROGRESS)
#define ST_CIF_ERR_PROFIBUS_CONFIGURATION    (SL_ERR_DC | SL_SNX_TOPO | SL_ST_ERR_PROFIBUS_CONFIGURATION)
#define ST_CIF_ERR_DELETE_DO                 (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_DO)
#define ST_CIF_ERR_DELETE_DO_P9_NOT_READY    (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_DO_P9_NOT_READY)
#define ST_CIF_ERR_DELETE_DO_P9_NOT_OK       (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_DO_P9_NOT_OK)
#define ST_CIF_ERR_DELETE_DO_ERR_PARAM       (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_DO_ERR_PARAM)

#define ST_CIF_ERR_DELETE_COMP_ERR_COMP_CU   (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_COMP_ERR_COMP_CU)
#define ST_CIF_ERR_DELETE_COMP_ERR_COMP_MAIN (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_COMP_ERR_COMP_MAIN)
#define ST_CIF_ERR_DELETE_COMP               (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_COMP)
#define ST_CIF_ERR_DELETE_COMP_DC_COUNTER    (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_COMP_DC_COUNTER)
#define ST_CIF_ERR_DELETE_COMP_ERR_PARAM     (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_COMP_ERR_PARAM)

#define ST_CIF_ERR_CHANGE_ID_NOT_VALID       (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_CHANGE_ID_NOT_VALID)
#define ST_CIF_ERR_CHANGE_ID_DUPLICATE       (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_CHANGE_ID_DUPLICATE)
#define ST_CIF_ERR_CHANGE_ID_ERR_SINAMICS    (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_CHANGE_ID_ERR_SINAMICS)
#define ST_CIF_ERR_CHANGE_ID_P9_NOT_OK       (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_CHANGE_ID_P9_NOT_OK)
#define ST_CIF_ERR_CHANGE_ID_PARAM_NOT_OK    (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_CHANGE_ID_PARAM_NOT_OK)

#define ST_CIF_ERR_CHANGE_ID_CU                     (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_CHANGE_ID_CU)
#define ST_CIF_ERR_REPLACEMENT_COMP_TYPE_NOT_OK     (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_REPLACEMENT_COMP_TYPE_NOT_OK)
#define ST_CIF_ERR_REPLACEMENT_COMP_P9910_NOT_OK    (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_REPLACEMENT_COMP_P9910_NOT_OK)
#define ST_CIF_ERR_REPLACEMENT_COMP_NO_TARGET_TOPO  (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_REPLACEMENT_COMP_NO_TARGET_TOPO)

#define ST_CIF_ERR_COMPONENT_WITHOUT_LED            (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_COMPONENT_WITHOUT_LED)
#define ST_CIF_ERR_COMPONENT_NOT_ASSIGNED           (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_COMPONENT_NOT_ASSIGNED)

#define ST_CIF_ERR_DELETE_COMP_SAFETY               (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_DELETE_COMP_SAFETY)

#define ST_CIF_ERR_SINAMICS_ERROR_ALARM             (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_SINAMICS_ERROR_ALARM)
#define ST_CIF_ERR_SINAMICS_ERROR_R3988             (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_SINAMICS_ERROR_R3988)

#define ST_CIF_ERR_S120COMBI_FCT_NOT_ALLOWED        (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_S120COMBI_FCT_NOT_ALLOWED)

#define ST_CIF_ERR_NX_OFFLINE                       (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_NX_OFFLINE)
#define ST_CIF_ERR_S120COMBI_TYPE                   (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_S120COMBI_TYPE)
#define ST_CIF_ERR_SOT_WRONG_R3988                  (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_SOT_WRONG_R3988)

#define ST_CIF_ERR_FW_UPD_DRIVES_NOT_READY          (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_FW_UPD_DRIVES_NOT_READY)                /* Error dcCfgFixPointVal ALL_DRIVES_ACCESSIBLE */
#define ST_CIF_ERR_FW_UPD_R3988_FATAL_FAULT         (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_FW_UPD_R3988_FATAL_FAULT)               /* Error R3988 = 1 Fatal fault */
#define ST_CIF_ERR_FW_UPD_TIMEOUT                   (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_FW_UPD_TIMEOUT)                         /* time out, couldn't wait any longer */

#define ST_CIF_ERR_HW_CFG_NO_SDB                    (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_HW_CFG_NO_SDB)                          /* HW-Config: sdbs missing */
#define ST_CIF_ERR_HW_CFG_NOT_ENOUGH_SLOTS          (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_HW_CFG_NOT_ENOUGH_SLOTS)                /* HW-Config: not enough slots for existing servos */

#define ST_CIF_ERR_TS_PORT_ALREADY_ASSIGNED         (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_TS_PORT_ALREADY_ASSIGNED)               /* error while adding components, port in target topology is already assigned*/

#define ST_CIF_ERR_HLA_WRONG_TELEGRAM_PB            (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_HLA_WRONG_TELEGRAM_PB)                     /* hydraulic module: wrong telegram in sdb, should be telegram 166 (PROFIBUS) */
#define ST_CIF_ERR_HLA_WRONG_TELEGRAM_PN            (SL_ERR_DC | SL_SNX_TOPO | ST_ERR_HLA_WRONG_TELEGRAM_PN)                     /* hydraulic module: wrong telegram in sdb, should be telegram 166 (PROFINET)*/

#endif // SL_DC_ERROR_INT_H
