///////////////////////////////////////////////////////////////////////////////
/*! \file   sltraceerrenumgrp.h
 *  \author Steve Menyhart
 *  \date   06-Oct-2006
 *  \brief  Header file that contains enum definitions for SlTraceErrEnum, SrcEnum, SeverityEnum
 *
 *  (C) Copyright Siemens AG A&D MC 2006.
 */
///////////////////////////////////////////////////////////////////////////////
#ifndef SL_TRACE_ERROR_ENUM_GROUPING
#define SL_TRACE_ERROR_ENUM_GROUPING(N,V,T)
#endif

//SL_TRACE_ERROR_ENUM_GROUPING(TRACE_NO_ERROR,                     0x00000000, "No error occured")
SL_TRACE_ERROR_ENUM_GROUPING(TRACE_UNSPECIFIED_ERROR,            0x81B00001, "An unspecified error occured")
SL_TRACE_ERROR_ENUM_GROUPING(TRACE_NOT_IMPLEMENTED,              0x81B00002, "This function is not implemented")

// TraceCore
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_DB_UNINITIALIZED,            0x81B01001, "NCVarTrace database is uninitialized")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_DB_ITEM_NOT_FOUND,           0x81B01002, "Item not found in NCVarTrace database, possible causes may be invalid password level, nck version, or variable name") // usually followed by SQL query string in error text
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_DB_UNABLE_TO_OPEN,           0x81B01003, "Unable to open NCVarTrace database (possible missing QSQLite Driver)")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_DB_ITEM_VERSION_FAILED,      0x81B01004, "Version check failed, possible causes may be variable too new for NCK version") // usually followed by SQL query string in error text
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_DB_COPY_FAILED,              0x81B01005, "Copy of symbol database to user directory failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_DB_REMOVE_840DSL_VDI_FAILED, 0x81B01006, "Removal of 840Dsl VDI symbols from database failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_DB_SYMBOL_IMPORT_FAILURE,    0x81B01007, "General failure merging VDI or PLC symbols")

SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_FILE_NOT_FOUND,              0x81B01010, "File not found") // usually followed by filename in error text
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_FILE_OPEN_ERROR,             0x81B01011, "File open error") // usually followed by filename in error text
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_FILE_READ_ERROR,             0x81B01012, "File read error") // usually followed by filename in error text
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_FILE_WRITE_ERROR,            0x81B01013, "File write error") // usually followed by filename in error text

SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_DOC_ERROR,                            0x81B01020, "XML dom document setContent error")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_PARSE_ERROR,                          0x81B01021, "XML parse error") // from PLCDataItem
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_ELEMENT_ERROR,                        0x81B01022, "XML element out of sequence or missing")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_SCHEMA_ERROR,                         0x81B01023, "XML schema validation error") // from CaptureSetup
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_ATTRIBUTE_MISSING_ERROR,              0x81B01024, "XML attribute missing")

SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_ATTRIBUTE_CONVERSION_TO_NUMBER_ERROR, 0x81B01025, "XML attribute did not convert to number")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_ATTRIBUTE_BOOLEAN_MISSING_ERROR,      0x81B01026, "XML attribute missing boolean")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_ATTRIBUTE_ENUM_NOT_FOUND_ERROR,       0x81B01027, "XML attribute enum not found")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_ATTRIBUTE_INVALID_KEY,                0x81B01028, "XML attribute has invalid key")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_SQL_QUERY_ERROR,                          0x81B01029, "SQLite query error")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_START_TRIGGER_ATTRIBUTE,              0x81B0102A, "XML attribute in start triggerCondition is invalid")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_STOP_TRIGGER_ATTRIBUTE,               0x81B0102B, "XML attribute in stop triggerCondition is invalid")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_ATTRIBUTE_INVALID_BTSS_PATH,          0x81B01030, "XML attribute has invalid or missing BTSS path. ")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_XML_ATTRIBUTE_INVALID_SYSTEM_VARIABLE,    0x81B01031, "XML attribute has invalid system variable designation. ")

SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_INVALID_PARAMETER,           0x81B01040, "Invalid parameter detected")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_INVALID_FUNCTION_CALLED,     0x81B01041, "Invalid function called")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_INVALID_NEW_KEY,             0x81B01042, "Could not generate unique key")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_INVALID_SERVO_SCALE_FACTOR,  0x81B01043, "Invalid Servo Scale Factor")
SL_TRACE_ERROR_ENUM_GROUPING(E_CORE_INVALID_MACHINE_MODEL,       0x81B01044, "Failed to create a valid machine model object")

// TraceServer
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DUPLICATE_NAME,             0x81B02001, "The session name already exists")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NO_SESSIONS,                0x81B02002, "No sessions currently exist")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVALID_NAME,               0x81B02003, "Session name must be less than 32 characters")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NO_PRIVILEGE,               0x81B02004, "Insufficient privilege for the requested operation")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESSION_OPEN,               0x81B02005, "The session has an open connection to it")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVALID_STATE,              0x81B02006, "The Trace Server is in an invalid state for the requested operation.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NO_TRACE_AVAIL,             0x81B02007, "No trace slots are available on the designated NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESSION_CLOSED,             0x81B02008, "A method call was made on session connection that has been closed.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SETEVENT_INVALID_MAXIMUM,   0x81B02009, "The maximum argument value cannot be less than the minimum  argument value.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVALID_OPTIONS,            0x81B0200A, "The option number is not a valid combination of options.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESSION_NOT_FOUND,          0x81B0200B, "The specified session is not found, it may have been renamed or deleted")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_ER_COL_NOT_FOUND,           0x81B02050, "Key item in find or remove not located")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_ER_COL_UNEXP_ERR,           0x81B02051, "Collection operation failed unexpectedly")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_ER_COL_KEY_INUSE,           0x81B02052, "Collection key aready used so is a duplicate or otherwise invalid")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVALID_SLOTKEY,            0x81B02053, "The designated trace slot key is invalid")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_NOT_FOUND,              0x81B02054, "A requested NCU was not present")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_NOT_WELL,               0x81B02055, "A requested NCU is not healthy - responsive")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STARTUP_FAILURE,            0x81B02056, "The trace server initialization failed.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SERVER_NOTREADY,            0x81B02057, "The trace server is not ready - check startup fail.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SERVER_DCAPIPROB,           0x81B02058, "The trace server could not load dcapi.dll")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SERVER_HMIREGPRB,           0x81B02059, "The trace server could access the Siemens HMI Base appPath Registry key value")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NETNAMES_FAIL,              0x81B0205A, "NCU netnames.ini parameter read failure")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCU_INIT_FAIL,             0x81B0205B, "NCU object initialization failure")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SERVER_INI_FAIL,            0x81B0205C, "The Trace Server could not read the TraceSrv.ini keys, verify that the file is present.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GET_NCU_STATE,              0x81B0205D, "The Trace Server could not read the TraceSrv.syf Trace Status file, verify that the file is present.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCK_SESS_REQUEST,           0x81B0205E, "An unexpected error was encountered requesting the NCK to reserve or unreserve a User slot for a designated session.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_REL_USER_SLOT,          0x81B0205F, "An attempt to release a trace user slot failed because the slot was in an unexpected state.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_USER_SESS_READ,         0x81B02060, "An attempt to read the session data associated with a user slot failed with an exception error.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_SESS_ARCV_READ,         0x81B02061, "An attempt to read a session archive file resulted in an unexpected error.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_UPDATE_SESS_DATA,       0x81B02062, "An attempt to update the NCU trace session data failed with an exception.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESS_PARSE_DESCRIPTOR,      0x81B02063, "An attempt to parse an archived session descriptor failed, cannot resore session.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESS_CANT_RESTORE_SLOT,     0x81B02064, "An attempt to restore a session failed due to a mismatch with the archived and existing user slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NODEL_SESSION_RECORDING,    0x81B02065, "An attempt to delete a session failed because the session is in a recording state, stop recording first.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_RESET_SESSION_UNLOADED, 0x81B02066, "An NCU Reset caused the session setup to be unloaded from the NCU and logging terminated,")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_SLCAP_EXCEED_MAX_NCU,   0x81B02067, "Error initializing NCUs, trying to initialize more NCUs than max number of allowed NCUs.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_SLCAP_MMC_INIT,         0x81B02068, "Error initializing NCUs while retrieving data with SlCap.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_LOGFILE_DATA_UNAVAIL,   0x81B02069, "Error, Log file data is unavailable due to session state or NCU reset/disconnect.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_SLCAP_CREATE_FAIL,      0x81B0206A, "Failed to create a valid SlCap object for the default or designated NCU.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESSION_SETUP_INIT,         0x81B0206B, "Uninitialized CSesSetup object in CSession")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESSION_FRAMEMGR_INIT,      0x81B0206C, "Uninitialized CFrameMgr object in CSession")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESSION_CAPTURE_INIT,       0x81B0206D, "Uninitialized CSessCapture object in CSession")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CAPTURE_PARAM,          0x81B0206E, "Invalid first parameter passed into a CDRVCapture method")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CAPTURE_PARAM2,         0x81B0206F, "Invalid second parameter passed into a CDRVCapture method")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_EVENT_READER_PARAM,     0x81B02070, "Invalid parameter passed into a CDRVEventReader method")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_EVENT_READER_RECORDS,   0x81B02071, "Uninitialized CDRVRecordCollection in CDRVEventReader object")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_DATA_STATE_COLL,        0x81B02072, "Unable to determine if the drive data is pending, available or completely processed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CAPTURE_GET_DATA_INIT,  0x81B02073, "Unable to find signal data array in a CDRVCapture method")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CAPTURE_GET_DATA_POINTS,0x81B02074, "Unable to find signal data points in a CDRVCapture method")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STILL_INITIALIZING_PLS_WAIT,0x81B02075, "The trace service is still initializing, please wait")


SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_FULL,                 0x81B02100, "The frame data capacity has been exceeded")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_POST_FULL,            0x81B02101, "The frame data capacity has met the post data requirement.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_INVALNUM,             0x81B02102, "The requested frame number is invalid, out of range")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_EMPTY,                0x81B02103, "There is no frame data available")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_INVALHANDLE,          0x81B02104, "The service was passed an invalid frame handle")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_BADDELSIZE,           0x81B02105, "The size of frames or TS specified for deletion is too large")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_TIMECONVERR,          0x81B02106, "An error ocurred attemting to convert time stamps")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_EXCPERR,              0x81B02107, "An unexpected exception was thrown in the frame manager")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_NOTIMPL,              0x81B02108, "This trace server frame feature is currently not supported/implemented")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_NOINTERVALS,          0x81B02109, "The client has requsted binary data, but specified zero intervals")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_MAXCAPACITY,          0x81B0210A, "The frame managers total data or time capacity has been exceeded")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_CONFIGERR,            0x81B0210B, "The frame managers failed to properly configure from domain setup")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_STATE_ERR,            0x81B0210C, "A request to initiate or terminate framing occurred at an unexpected or invalid time")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_UNSPECIFIED_DROPOUT,  0x81B0210D, "while adding a timeslice, an unspecified dropout was detected")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_NO_RESTORE,         0x81B02200, "Put capture failed AND unable to restore previous capture")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_PREV_PRESERV,       0x81B02201, "Put capture failed, but able to preserve previous capture setup")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TOO_MANY_SIG,       0x81B02202, "Put capture failed, exceeded data manager limitiations on signals")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TOO_MANY_EVT,       0x81B02203, "Put capture failed, too many events for that NCU's slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TOO_MANY_S_E,       0x81B02204, "Put capture failed, too many SIGNALS for individual event for that NCU's slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_UNSUP_TYPE,         0x81B02205, "Put capture failed, found unsupported data type on a signal")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TIMESLICEERR,       0x81B02206, "Put capture failed, a timeslice specified on cyclic did not match current capabilities")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_READ_PRIVERR,       0x81B02207, "Put capture failed, an item to be read required higher password level permission")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TRIG_PRIVERR,       0x81B02208, "Put capture failed, a trigger item attempt to read failed password level required permission")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TRIGUNSUP_TYPE,     0x81B02209, "Put capture failed, found unsupported data type on a signal")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_IPOSVOTIMEERR,      0x81B0220A, "Put capture failed, if svo event used, must have multiplier of 1 on either ipo1 or ipo2 sample rate")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TIMESLICEERR2,      0x81B0220B, "Put capture failed, a timeslice specified on cyclic ipo2 did not match current capabilities")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_MAXCAPACITY,        0x81B0220C, "The specified capacity exceeds the server's max capacity")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_CREATE_ARCHIVE,     0x81B0220D, "Writing the archive file for the setup failed.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_PLCEVT_UNSUP,       0x81B02250, "Put capture failed, plc events not supported for the targeted ncu release")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_COMPLX_UNSUP,       0x81B02251, "Put capture failed, complex triggers not supported for the targeted ncu release")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_START_UNSUP,        0x81B02252, "Put capture failed, start triggers not supported for the targeted ncu release")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_REARM_UNSUP,        0x81B02253, "Put capture failed, auto rearm not supported ...")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_POWONSTART_UNSUP,   0x81B02254, "Put capture failed, auto power on start not supported ...")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_DELAY_UNSUP,        0x81B02255, "Unsupported feature")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_INVALPOINTER,       0x81B02256, "In invalid object pointer was returned")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_CFG_WRITE_ERR1,     0x81B02257, "Error writing config item, ivar returned 0x81000303 name not found in current release, is nc6. mapping file present?")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_CFG_WRITE_ERR2,     0x81B02258, "Error writing config item, ivar returned 0x85000903 error code on write attemp")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_CFG_WRITE_ERR3,     0x81B02259, "Error writing config item, ivar returned 0x8500090a error code on write attempt")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_1,    0x81B0225A, "Error attempting to arm events just prior to start, general error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_2,    0x81B0225B, "Error attempting to arm events just prior to start eventActiveStatus indicated reason base + reason code")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_2_1,  0x81B0225C, "Error attempting to arm events just prior to start. Reading eventActiveStatus indicated reason 1")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_2_2,  0x81B0225D, "Error attempting to arm events just prior to start. Reading eventActiveStatus indicated reason 2, insuf NCU resources")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_2_3,  0x81B0225E, "Error attempting to arm events just prior to start. Reading eventActiveStatus indicated reason 3, record size > 400")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_2_4,  0x81B0225F, "Error attempting to arm events just prior to start. Reading eventActiveStatus indicated reason 4, can't create ncu file")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_2_5,  0x81B02260, "Error attempting to arm events just prior to start. Reading eventActiveStatus indicated reason 5, too many servo items")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_OTH,  0x81B02261, "Error attempting to arm events just prior to start")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS1,  0x81B02262, "Error attempting to arm events, var spec 1 btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS2,  0x81B02263, "Error attempting to arm events, var spec 2 btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS3,  0x81B02264, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS4,  0x81B02265, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS5,  0x81B02266, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS6,  0x81B02267, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS7,  0x81B02268, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS8,  0x81B02269, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS9,  0x81B0226A, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS10, 0x81B0226B, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS11, 0x81B0226C, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS12, 0x81B0226D, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS13, 0x81B0226E, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS14, 0x81B0226F, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS15, 0x81B02270, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS16, 0x81B02271, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS17, 0x81B02272, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS18, 0x81B02273, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS19, 0x81B02274, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS20, 0x81B02275, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS21, 0x81B02276, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS22, 0x81B02277, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS23, 0x81B02278, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS24, 0x81B02279, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_VS25, 0x81B0227A, "Error attempting to arm events, var spec x btss info not liked.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_OBTAIN_IPO_TRIG_STATE,      0x81B0227B, "Error obtaining the trigger state in slot containing trigger")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVALID_IPO_TRIG_STATE,     0x81B0227C, "Error trigger not allowed to be in passive state for enabled trigger")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_OBTAIN_TRIG_SLOT_KEY,       0x81B0227D, "Error obtaining session SlotKey for NCU Slot that has trigger enabled")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_INI_FILESIZE_FAIL,  0x81B0227E, "Error writing the NCK Trace file size designated in the TraceSrv.ini ")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVAL_SIGNAL_REJECTED,      0x81B0227F, "Error attempting to arm events. A signal specifies a variable that is considered invalid or does not exist. See error stack for additional info")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVAL_SIGNAL_ACC_DENIED,    0x81B02280, "Error attempting to arm events. A signal is disabled and can not be traced. See error stack for additional info")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_MULTICHAN_NO_AXIS_CFG_DENIED, 0x81B02281, "Error attempting to trace the same event on more than one channel when one of those channels has no axes configured. Try to trace the event on only one channel.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOSAMPLE_RATES_INCOMPATIBLE, 0x81B02282, "The Trace session specifies different IPO sample rates for  IPO1 and  IPO2, and the NCK version is less than 67.00.00. Please change the settings to use the same sample rate.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ARM_LIST_FAILED_2_6,  0x81B02283, "Error attempting to arm events just prior to start. Reading eventActiveStatus indicated reason 6, too many plc items")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SETUP_DRV_IPO_NOT_SUPPORTED_1, 0x81B02284, "Error attempting to putSetup that has both IPO and DRV signals present")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SETUP_DRV_IPO_NOT_SUPPORTED_2, 0x81B02285, "Error attempting to putSetup that has signals belonging to more than one CU. All signals must be from same CU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SETUP_DRV_IPO_NOT_SUPPORTED_3, 0x81B02286, "Error attempting to putSetup that has more than 8 different DRV signals present")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVAL_SIGNAL_KEY,              0x81B02287, "Invalid SignalKey")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_TRIG_NOT_CONFIGURED,     0x81B02288, "Trigger condition not configured just prior to activating the trace engine")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_START2,                    0x81B02289, "Error attempting to start the DRV trace, unexpected empty flags")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_TRIG_NOT_CONFIG2,          0x81B0228A, "Call to HasStartTriggerFired failed because no trigger was configured")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_AST_START_FAULT,           0x81B0228B, "A recent call to start the DRV trace resulted in an error being reported while monitoring for IsOffloadComplete")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_AST_CANCEL_FAULT_DETECTED,        0x81B0228C, "A recent DRV trace engine fault has been detected most likely due to manual cancel. Trace is set into a fault condition")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_AST_UNEXPECT_CALC_POINTS,  0x81B0228D, "Unexpected result attempting to calculate points / intervals as obtained from AST services")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_EVENT_ACTIVE, 0x81B0228E, "Couldn't configure the session, the previous recording was not closed properly")


SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESSION_CAPTURE,            0x81B02300, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CAPTURE_SETUP,              0x81B02301, "Unable to commit setup")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CAPTURE_ALLOC,              0x81B02302, "Unable to alloc memory")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FIXUP_SVO_SCALE,            0x81B02303, "Unable to apply scaling for servo signals")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CREATE_ONLINE_INFO,         0x81B02304, "Unable to establish online information")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EVENT_READER,               0x81B02340, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READER_INIT,                0x81B02341, "Unable to initialize CEventReader")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READER_ALLOC,               0x81B02342, "Unable to alloc memory")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READER_QUEUE,               0x81B02343, "Unable to read CEventReader's queue")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READER_NO_DATA_AVAIL,       0x81B02344, "Data not passivated")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READER_DATA_COMPLETE,       0x81B02345, "All data consumed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EVENT_ID,                   0x81B02346, "Unexpected ID")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EVENT_RECORD_INIT,          0x81B02347, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EVENT_RECORD_COLL_INIT,     0x81B02348, "Attempt to use CEventRecordCollection when in an unitialized state")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EVENT_RECORD_COLL_PARAM,    0x81B02349, "Invalid parameter passed into a CEventRecordCollection method")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_COLL_INIT,       0x81B0234A, "Attempt to use CDRVRecordCollection when in an unitialized state")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_COLL_PARAM,      0x81B0234B, "Invalid parameter passed into a CDRVRecordCollection method")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_COLL_ITEM_INIT,  0x81B0234C, "CDRVRecord item in CDRVRecordCollection is in an unitialized state")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_SIGNAL_INIT,     0x81B0234D, "Collection of CDRVSignalItems in CDRVRecord is in an unitialized state")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_SIGNAL_KEY,      0x81B0234E, "CDRVRecord object detected an invalid key for collection of CDRVSignalItem")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_CAPTURE_INIT,    0x81B0234F, "CDRVCapture item in CDRVRecord is in an unitialized state")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_DATA_STATE_ASYNC,0x81B02350, "CDRVRecord detected signal data delivered at different times")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_DATA_POINTS_ASYNC,0x81B02351, "CDRVRecord detected unused signal data points at end of stream")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_DATA_STATE_UNKNOWN,     0x81B02352, "Expected data state to be available, pending or complete")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_SIGNAL_DATA_TYPE_MISMATCH, 0x81B02353, "Data type returned from drive trace engine isn't the designated data type for signal name")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_SIGNAL_UNSUP_DATA_TYPE, 0x81B02354, "Put capture failed, found unsupported data type on a drive signal")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_NO_SIGNAL_DATA,  0x81B02355, "CDRVRecord expected drive signal data arrays to be already cached")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_NO_SIGNAL_POINTS,0x81B02356, "CDRVRecord expected drive signal points to be already cached")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SESS_STATE,                 0x81B02360, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STATE_STIMULUS,             0x81B02361, "Invalid state stimulus")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STATE_CHANGE,               0x81B02362, "State change fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STATE_SET,                  0x81B02363, "State change request fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STATE_ARMED,                0x81B02364, "State Armed failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STATE_RESERVED,             0x81B02365, "State Reserved failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STATE_RECORDING,            0x81B02366, "State Recording failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STATE_STOPPED,              0x81B02367, "State Stopped failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STATE_UNKNOWN,              0x81B02368, "State Stopped failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_STATE_MUTEX,                0x81B02369, "State change mutex")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_CAPTURE,                0x81B02400, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_CAPTURE_INIT,           0x81B02401, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_GETDATA_BEGIN,          0x81B02402, "Invalid GetData parameter")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_GETDATA_LENGTH,         0x81B02403, "Invalid GetData parameter")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_FINAL_DATA,             0x81B02404, "0xE0008404")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_OBJ_COLL,              0x81B02430, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_FINAL_CONSTRUCT,       0x81B02431, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_COLL_MUTEX,            0x81B02432, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_OBJ_MUTEX,             0x81B02433, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_OBJ_COUNT,             0x81B02434, "Should never occur")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_OBJ_NOT_FOUND,         0x81B02435, "Key not in collection")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_OBJ_SKIPPED,           0x81B02436, "Not keeping up, still found another key")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_COLL_EMPTY,            0x81B02437, "Collection empty")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_OBJ_KEY,               0x81B02438, "Invalid key")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_OBJ_GET,               0x81B02439, "Invalid GetFileObject parameter")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_OBJ_CREATE,            0x81B0243A, "New filed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_COLL_RESOURCE_MAX,     0x81B0243B, "Combined file sizes exceeded resource")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_COLL_CALC_SIZE,        0x81B0243C, "CalcMaxFileSize failed")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_START,          0x81B0243D, "Create/resume thread error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_STOP,           0x81B0243E, "Thread shutdown error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_STOPTIME,       0x81B0243F, "Thread shutdown error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_CANCEL,         0x81B02440, "Offload thread shutdown error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_WATCHDOG_STARTUP,       0x81B02441, "ReadPipe watchdog thread startup error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_WATCHDOG_CANCEL,        0x81B02442, "ReadPipe watchdog thread shutdown error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_PENDING,        0x81B02443, "Failed to read seamed file")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_STATUS,         0x81B02444, "Failed to read seamed file")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_FILE_DELETE,            0x81B02445, "NCK file delete fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_FILE_DELETE_DENIED,     0x81B02446, "Offload in progress")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_COLL_GIT,              0x81B02447, "Fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_MUTEXTIMEDWAIT_PARAM1,      0x81B02448, "parameter 1 passed to MutexTimedWait fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_MUTEXTIMEDWAIT_PARAM2,      0x81B02449, "parameter 2 passed to MutexTimedWait fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_MUTEXTIMEDWAIT_PARAM3,      0x81B0244A, "parameter 3 passed to MutexTimedWait fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_MUTEXTIMEDWAIT_PARAM4,      0x81B0244B, "parameter 4 passed to MutexTimedWait fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_FILE_OPEN,              0x81B0244C, "Failed to open file in _DESKTOP mode")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_WATCHDOG_MUTEX,         0x81B0244D, "ReadPipe watchdog thread shutdown error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_MUTEX,          0x81B0244E, "Offload thread shutdown error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_FALSE_START,    0x81B0244F, "Offload thread unexpectedly restarted")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_EVENTING,       0x81B02450, "Offload wakeup/suspend eventing error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CALC_TIME_FROM_STARTLOG,    0x81B02451, "Calculate time from start of frame")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CALC_TIME_FROM_GTS_STARTLOG,0x81B02452, "Calculate time from start of frame")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_WRITE_BUFFER_INIT,     0x81B02453, "Seam write buffer uninitialized")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_MIN_COUNT_ON_DISCARD,  0x81B02454, "Seam count below minumum when attemting to write to the seam buffer")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_MIN_COUNT_ON_WRITE,    0x81B02455, "Seam count below minumum when attemting to discard seams from buffer")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_BEGIN_PARAM,    0x81B02460, "OffLoadBegin method parameter fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_BEGIN_FAIL,     0x81B02461, "OffLoadBegin method fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_PARAM,          0x81B02462, "Offload method parameter fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_OFFLOAD_FAIL,           0x81B02463, "Offload method fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_RECORD_INFO_PARAM,      0x81B02464, "GetRecordInfo method parameter fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_RECORD_INFO_FAIL,       0x81B02465, "GetRecordInfo method fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_RECORD_SIZE_FAIL,       0x81B02466, "GetRecordInfo method fail")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_STARTLOG_READ,          0x81B02467, "NCRead of start log failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_STARTLOG_LEN,           0x81B02468, "NCRead of start log failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_STARTLOG_ACC,           0x81B02469, "Start log safe array access")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_TIMESLICE_TOO_SMALL,    0x81B0246A, "Data not passivated")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_EVENT_ID,               0x81B0246B, "NCRead find event")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_EVENT_READ,             0x81B0246C, "NCRead of event record(s) failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_EVENT_LEN,              0x81B0246D, "NCRead of event record(s) failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_EVENT_RECORD_LENGTH,    0x81B0246E, "NCRead of event record(s) failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_EVENT_ACC,              0x81B0246F, "Event record(s) safe array access")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_NO_DATA_AVAIL,          0x81B02470, "Data not passivated")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_SERIALNO_SKIPPED,       0x81B02471, "Missing SerialNo - data Loss due to NCK File Overrun")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_EVENTCNT_SKIPPED,       0x81B02472, "EventCnt jumped by more than one")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_FILE_OPEN,             0x81B02473, "Fopen")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_FILE_PREV_OPEN,        0x81B02474, "Previously opened")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_FILE_NOT_OPEN,         0x81B02475, "Fopen")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_FILE_CLOSE,            0x81B02476, "Fclose")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_FILE_DELETE,           0x81B02477, "Remove")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_FILE_TIME_SPAN,        0x81B02478, "Unexpected time span of file record's timeslices")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_HEADER_WRITE,          0x81B02479, "Failed to write seamed header")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_STARTLOG_WRITE,        0x81B0247A, "Failed to write seamed startlog")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_BLOCK_WRITE,           0x81B0247B, "Failed to write seamed event records")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_WRITE_LENGTH,          0x81B0247C, "No event records for seam write")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_EVENT_TIME,            0x81B0247D, "No event time for seam write")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_EVENT_READ,            0x81B0247E, "Failed to read seam")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_BLOCK_READ,            0x81B0247F, "Failed to read seam")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_HEADER_READ,           0x81B02480, "Failed to read seamed header")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_HEADER_VERSION,        0x81B02481, "Failed to read seamed header")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_OVERRUN,               0x81B02482, "Not keeping up")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_END_OF_FILE,           0x81B02483, "Data not passivated")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_STARTLOG_READ,         0x81B02484, "Failed to read seamed startlog")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_READ_BUF_LEN,          0x81B02485, "Read buf too small")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_REFERENCED,            0x81B02486, "Didn't call release")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SEAM_CAPACITY_LIMIT,        0x81B02487, "Seaming cancelled because at capacity")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FILE_OBJ_CANT_RESET,        0x81B02488, "Not resetable")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SYS_TRIG_MODE_UNSUP,        0x81B02489, "Unsupported feature")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EXCEPTION_REPORTED,         0x81B0248A, "An unexpected exception was captured")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_BCD_TIME_ERROR,             0x81B0248B, "A BCD time could not be converted to file time")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_IPOSVOTIME_BAD,     0x81B0248C, "Put capture failed, the svo sample rate is incorrect or incompatible with the IPO rates specified")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_FILESIZE_FAIL,      0x81B0248D, "The specified maximum file size capacity can not be granted by the NCU due to current resourse limitations.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TOO_MANY_SVO,       0x81B0248E, "Put capture failed, exceeded $MN_MM_PROTOC_NUM_SERVO_DATA[user slot] differnt servo items.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_MAX_DATA_LISTS,     0x81B0248F, "Too many different events in the trace setup. Reduce the number of unique events in Setup Waveforms or increase the configuration item MM_PROTOC_NUM_ETPD_STD_LIST[x].")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_NO_DATA_FOUND,          0x81B02490, "No trace data was found in the NCK's binary trace log file.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_DATA_UPLOAD_TIMEOUT,    0x81B02491, "Uploaded trace data is less than the amount captured in NCK's binary trace log file.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_MERGED_TIMESLICE_TOO_SMALL, 0x81B02492, "merged event's time smaller than previously merged event's time")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TRIG_NOT_DRV,       0x81B02493, "Put capture failed, a trigger was found, but not of expected DRV type")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TRIG_DELAY_NOT_SUPP,0x81B02494, "Put capture failed, a trigger specified a delay time that was not supported")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_DRV_OFFLOAD_MECH_UNSUP,0x81B02495, "Put capture failed, a offload indicated something other than deferred for DRV trace")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRVSIGNALVAR,               0x81B02496, "Invalid DRV BICO address specification to read")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_DRV_STOP_MECH_UNSUP,0x81B02497, "Put capture failed, the time limit or capacity limit parameters were not correct")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TRIG_NOT_TRACIBLE,  0x81B02498, "Put capture failed, the trigger is not a valid tracible trigger")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_DRV_VAR_NOT_TRACIBLE,0x81B02499, "Put capture failed, the DRV variable is not a valid tracible DRV variable")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_SWITCHING_LOCK_FAILED, 0x81B0249A, "Unable to obtain NCU switching lock")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_NCU_SWITCHING_UNLOCK_FAILED, 0x81B0249B, "Unable to do NCU switching unlock")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_PIPE_FAIL,         0x81B024A0, "IMC file pipe general failure.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_NOT_CLOSED,        0x81B024A1, "IMC file needs to be closed for this operation.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_DIR,               0x81B024A2, "IMC file directory not established.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_NAME,              0x81B024A3, "IMC file name not established.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_WATCHDOG_START,         0x81B024A4, "Could not start up IMC file read watchdog.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_WATCHDOG_INIT,          0x81B024A5, "IMC file read watchdog started but failed during initialization.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_WATCHDOG_START_FAIL,    0x81B024A6, "Could not star up IMC file read watchdog.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_WATCHDOG_RUNNING,       0x81B024A7, "IMC file read watchdog needs to be stopped for this operation.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_WATCHDOG_KILL,          0x81B024A8, "IMC file read watchdog needs to be stopped for this operation.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_DATA_SOURCE,            0x81B024A9, "IMC file's NCU data source needs to be established for this operation.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_ALREADY_OPEN,      0x81B024AA, "Attempt to open IMC file when already open.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_OPEN,              0x81B024AB, "IMC file could not be opened.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_OPEN_FAIL,         0x81B024AC, "IMC file could not be opened.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_CLOSE_FAIL,        0x81B024AD, "IMC file could not be closed.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_DELETE_FAIL,       0x81B024AE, "IMC file could not be deleted.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_PIPE_EVENT,        0x81B024AF, "IMC file event could not be established.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_PIPE_EVENT_FAIL,   0x81B024B0, "IMC file event could not be established.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_READ_PARAM,        0x81B024B1, "Invalid IMC file read parameter.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_READ_FAIL,         0x81B024B2, "IMC file read failure.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_DATA_NOT_RELEASED,      0x81B024B3, "No IPO Trace data was released from last read.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_READ_TIMER_FAIL,   0x81B024B4, "IMC file read timer failure.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_DATA_ACCESS,       0x81B024B5, "IMC file read data acess failure.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_DATA_LEN,          0x81B024B6, "IMC file read data acess failure.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_DATA_READ,         0x81B024B7, "IMC file read data acess failure.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FILE_DATA_FAIL,         0x81B024B8, "IMC file read data acess failure.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FREE_READ_BUFFER,       0x81B024B9, "Attempt to free more than IMC file read buffer.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_READ_BUFFER_MOVE,       0x81B024BA, "IMC file read buffer could not be consolidated.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_FREE_READ_BUFFER_FAIL,  0x81B024BB, "IMC file free read buffer failure.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_TUNE_OFFLOAD_PARAM,     0x81B024BC, "Invalid IMC file offload tuning parameters.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_TUNE_OFFLOAD_FAIL,      0x81B024BD, "IMC file offload tuning failure.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_BUFFER_OVERRUN,         0x81B024BE, "IMC buffer was overrun by slcap pipe callback.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IMC_BUFFER_TOO_SMALL,       0x81B024BF, "IMC buffer is too small to fit data from slcap pipe callback.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCUWRITESINGLEVAR_PARAM1,  0x81B024C0, "Invalid BTSS address specification to write to NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCUWRITESINGLEVAR_PARAM2,  0x81B024C1, "Invalid BTSS value to write to NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCU_WRITE_EXCEPTION,       0x81B024C2, "Server error while updating BTSS variable")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCU_READ_EXCEPTION,        0x81B024C3, "Server error while reading BTSS variable")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCU_READ_FAIL,             0x81B024C4, "Error while processing returned BTSS variable read from NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCUREADSINGLEVAR_PARAM1,   0x81B024C5, "Invalid BTSS address specification to read from NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCUREADSINGLEVAR_PARAM2,   0x81B024C6, "Invalid return specification to place value read from NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCUREADMULTIVAR_PARAM1,    0x81B024C7, "Invalid BTSS address specification to read")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCUREADMULTIVAR_PARAM2,    0x81B024C8, "Invalid return specification to place value read from NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCUGETFILESTATUS_PARAM,    0x81B024C9, "Invalid return specification to place file status read from NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCUGETUSERSESS_PARAM,      0x81B024CA, "Invalid user slot specification for IPO trace")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_SERIALNO_SKIPPED_2,     0x81B024CB, "Missing SerialNo - Data Loss due to NCK FIFO overrun")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_SERIALNO_SKIPPED_3,     0x81B024CC, "Missing SerialNo - Data Loss due to NCK IPO Cycle Overrun")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCU_ADVISE_DATA_ERROR,     0x81B024CD, "An attempt to receive trace diagnostic advise data failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCU_ADVISE_CONFIG_ERROR,   0x81B024CE, "An attempt to configure or manage trace diagnostic advise data failed")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCU_MULTIWRITE_PARAM1,     0x81B024CF, "Invalid BTSS address specification to write")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCU_MULTIWRITE_PARAM2,     0x81B024D0, "Invalid specification to place write results from NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CNCU_MULTIWRITE_EXCEPTION,  0x81B024D1, "Server error while updating BTSS variable")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GETWRITERESULT_VALUE,       0x81B024D2, "error extracting write results after writing to NCU variables")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GETWRITERESULT_PARAM1,      0x81B024D3, "invalid BTSS address specification input parameter")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GETWRITERESULT_PARAM2,      0x81B024D4, "invalid write results input parameter")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GETWRITERESULT_PARAM3,      0x81B024D5, "invalid write results output parameter")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GETWRITERESULT_PARAMS,      0x81B024D6, "invalid parameters for extracting write results")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_ADD_TO_DATA_LIST,           0x81B024D7, "error configuring IPO Trace data lists")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_WRITE_TRIGGER_COMPARISON,   0x81B024D8, "error configuring IPO Trace trigger comparison")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_WRITE_TRIGGER_COMP_VALUE,   0x81B024D9, "error configuring IPO Trace trigger comparison values")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_WRITE_TRIGGER_COMP_TYPE,    0x81B024DA, "error configuring IPO Trace trigger comparison values - wrong data type")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CAPTURE_SETTINGS_TRIG_INIT, 0x81B024DB, "error initialization IPO Trace capture and trigger settings")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAPTURE_SETTINGS_INIT,  0x81B024DC, "error initialization IPO Trace capture settings")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_TRIGGER_SETTINGS_INIT,  0x81B024DD, "error initialization IPO Trace trigger settings")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_BUILD_EVENT_AND_LIST,       0x81B024DE, "error building up IPO Trace's event based data lists")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_CYCLIC_DATA_MISSING,    0x81B024DF, "Cyclic data missing, NCK data read failure, variable undefined")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SLCONFIG_INDEX_OUT_OF_RANGE,0x81B024E0, "Index into slConfig collection is out of bounds")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_OBJECT_NOT_TYPE_IPOCONFIG,  0x81B024E1, "Object found in slConfig collection is not a CIPOConfig object")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_UNKNOWN_SLCONFIG_TYPE,      0x81B024E2, "Object found in slConfig collection is not a type CIPOConfig or CDRVConfig")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GET_IPOCONFIG_OBJECT,       0x81B024E3, "Object found in slConfig collection for CIPOConfig is null")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GET_IPOCONFIG_NCU_OBJECT,   0x81B024E4, "CIPOConfig object has no assigned NCU")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_CONFIG_PARAM,           0x81B024E5, "Invalid parameter passed into a CIPOConfig method")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_PARAM,           0x81B024E6, "Invalid parameter passed into a CDRVConfig method")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_EVENT_READER_ALLOC,     0x81B024E7, "Failed to create IPO Event Reader")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_EVENT_READER_ALLOC,     0x81B024E8, "Failed to create DRV Event Reader")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_CONFIG_SESSION_INIT,    0x81B024E9, "Uninitialized CSession object in CIPOConfig")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPO_CONFIG_NCU_INIT,        0x81B024EA, "Uninitialized CNCU object in CIPOConfig")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_SAMP_RATE,      0x81B024EB, "Error in SetSampleRate")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_REC_TIME,       0x81B024EC, "Error in SetRecordingTime")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_UNEXP_NULL_ENGINE,  0x81B024ED, "Unexpected null pointer for DRVTraceEngine")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SIGNAL_ADD,         0x81B024EE, "Error adding a signal to AST DRV Engine")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_TRIG_TYPE,      0x81B024EF, "Error in SetTriggerType")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_TRIG_THRES,     0x81B024F0, "Error in SetTrigger - setting threshold")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_TRIG_SIGNAL,    0x81B024F1, "Error in SetTrigger - setting trigger signal")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_TRIG_TIMEDELAY, 0x81B024F2, "Error in SetTrigger - setting trigger timedelay")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_TRIG_TOL1,      0x81B024F3, "Error in SetTrigger - setting trigger Tolerance 1")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_TRIG_TOL2,      0x81B024F4, "Error in SetTrigger - setting trigger Tolerance 2")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_TRIG_CONDMASK,  0x81B024F5, "Error in SetTrigger - setting trigger CONDITION mask")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_SET_TRIG_BITMASK,   0x81B024F6, "Error in SetTrigger - setting trigger bit mask")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_INTERPRET_REC_SIZE, 0x81B024F7, "Error in CDRVRecord.InterpretRecord. The list size did not match the signal count")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CONFIG_ADD_DRV_CONFIG,     0x81B024F8, "Error in adding a config record then unable to find it again")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SETUP_ALLOC,                   0x81B024F9, "Error allocating memory during SesSetup operations")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_START,                     0x81B024FA, "Error in attempting to start the DRV trace")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_STOP,                      0x81B024FB, "Error in attempting to stop the DRV trace")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CLEARDATA,                 0x81B024FC, "Error in attempting to cleardata the DRV trace")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RESET,                     0x81B024FD, "Error in attempting to reset the DRV trace")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_CAPTURE_ENGINE_INIT,       0x81B024FE, "Uninitialized CDRVEngine object in CDRVCapture")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_RECORD_SAMPLE_RATE_INIT,   0x81B024FF, "Uninitialized sample interval in CDRVRecord")


SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_OUTOFMEMORY,                0x81B02500, "Out of memory")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVALID_ARG,                0x81B02501, "Invalid Argument")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_MUTEX_ACQUIRE,              0x81B02502, "Error acquiring a mutex")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_MUTEX_RELEASE,              0x81B02503, "Error releasing a mutex")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FAIL,                       0x81B02504, "Unexpected software failure error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EVENT_RESET,                0x81B02505, "Error resetting an event")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EVENT_SET,                  0x81B02506, "Error signaling an event")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EVENT_WAIT,                 0x81B02507, "Error waiting on an event")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_EVENT_TIMED_WAIT,           0x81B02508, "Error waiting on an event")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_BAD_XML_WRITESPAN,          0x81B02510, "Malformed XML")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_BAD_XML_WRITESPAN_LENGTH,   0x81B02511, "Attribute with Value Exceeds Writespan")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READING_MIN_STDEVENTCOUNT,  0x81B02512, "Error reading StdEventCount in the TraceSrv.ini")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READING_MIN_NUMSERVODATAITEMS,0x81B02513,"Error reading NumServoDataItems in the TraceSrv.ini")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READING_MIN_STDLISTCOUNT,   0x81B02514, "Error reading StdListCount in the TraceSrv.ini")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READING_MIN_FILEMEMORYTYPE, 0x81B02515, "Error reading FileMemoryType in the TraceSrv.ini")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READING_MIN_NCKBUFFERSIZE,  0x81B02516, "Error reading NckBufferSize in the TraceSrv.ini")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READING_MIN_NCKFILESIZE,    0x81B02517, "Error reading NckFileSize in the TraceSrv.ini")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READING_MIN_NUMSESSLOGFILES,0x81B02518, "Error reading NumSessLogFiles in the TraceSrv.ini")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READING_IPOTRACE_RESOURCES, 0x81B02519, "Error reading resource configuration for IPO Trace slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_WRITING_IPOTRACE_RESOURCES, 0x81B0251A, "Error writing resource configuration for IPO Trace slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CHECKING_IPOTRACE_RESOURCES,0x81B0251B, "Error checking resource configuration for IPO Trace slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOTRACE_RESOURCES_NOT_MET, 0x81B0251C, "Error in resource configuration for IPO Trace slots")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOTRACE_WRITE_PRIVILEDGE,  0x81B0251D, "IPO Trace configuration wasn’t updated due to insufficient write priviledges. Must be at Manufacturing password level.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOTRACE_MEMORY_REORG,      0x81B0251E, "IPO Trace configuration wasn’t updated due to item requiring memory reorganization. Item must be manually changed.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOTRACE_LOW_RESOURCE,      0x81B0251F, "IPO Trace slot selected for this session does not meet the minimum configuration set in the tracesrv.ini file.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOTRACE_PROFILE_INVALID,   0x81B02520, "TraceSrv.ini setting not a valid IPO Trace configuration.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOTRACE_PROFILE_TOO_LOW,   0x81B02521, "TraceSrv.ini setting is too low of a value for IPO Trace configuration.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOTRACE_NO_CONFIGURED_SLOTS,0x81B02522, "No IPO Trace slots are configured on NCK")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOTRACE_CONFIGURED_SLOTS,   0x81B02523, "Error determining the total configured IPO Trace slots on NCK")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_IPOTRACE_RESERVED_SLOTS,    0x81B02524, "Error determining the total reserved IPO Trace slots on NCK")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_WRITING_IPOTRACE_RESOURCES2,0x81B02525, "Error writing resource configuration for IPO Trace slot")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CREATE_DATA_EVENTS_THREAD,  0x81B02527, "Error creating ReportDataEventsThread")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CREATE_INITIALIZE_THREAD,   0x81B02528, "Error creating CTraceInitializeThread")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_CREATE_SESSION_THREAD,      0x81B02529, "Error creating SessionThread")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SLCAP_NCUPLOAD_TIMEOUT,     0x81B0252A, "SlCap Communications timeout reading status file from NCK")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SLCAP_READWRITE_TIMEOUT,    0x81B0252B, "SlCap Communications timeout reading or writing variable on NCK")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SLCAP_GENERAL_FAILURE,      0x81B0252C, "SlCap general failure communicationing to NCK")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DCAPI_OFFLINE,              0x81B0252D, "DataCache service reports it is offline")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SLCAP_MSG_REM_ABORT,        0x81B0252E, "Error, request aborted, the NCK is disconnected or non responsive")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SETUP_INITIALIZATION_FAILED,   0x81B0252F, "TraceSetup constructor failed")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_READING_IPOTRACE_ENABLED,   0x81B02530, "Error reading user active state for IPO Trace slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_REPORTING_IPOTRACE_ENABLED, 0x81B02531, "Error reading user active state for IPO Trace slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_REPORTING_IPOTRACE_ENABLED2,0x81B02532, "Error reading user active state for IPO Trace slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_WRITING_IPOTRACE_ENABLED,   0x81B02533, "Error writing user active state for IPO Trace slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_WRITING_IPOTRACE_ENABLED2,  0x81B02534, "Error writing user active state for IPO Trace slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_WRITING_IPOTRACE_ENABLED3,  0x81B02535, "Error writing user active state for IPO Trace slot")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SLCONFIG_COLLECTION_EMPTY,  0x81B02536, "Session Setup's slConfigCollection is empty")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_SLCONFIG_COLLECTION_ITEM_INIT, 0x81B02537, "Found unitialized item in Session Setup's slConfigCollection")


SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_UPDATE_BCD_RESOLUTION,      0x81B02540, "Error determining NCK's BCD Clock Resolution")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GET_BCD_RESOLUTION,         0x81B02541, "Error obtaining NCK's BCD Clock Resolution")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TIMESLICEERR3,      0x81B02542, "Put capture failed, a timeslice specified on DRV event did not match current capabilities")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_STOP_UNSUP,         0x81B02543, "Put capture failed, a stop trigger was specified but is unsupported in DRV trace")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_GET_UNINITIALIZED,          0x81B02544, "Call to GetHasTypesOfSignals failed due to unitialized data")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_TRIG_NOT_CONFIGURED,    0x81B02545, "Call to HasStartTriggerFired failed because no trigger was configured")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_ENGINE_BAD_STATE,       0x81B02546, "Call was made into DRV Engine and a invalid or unexpected AST_none state was returned while in ARMed state.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_PUT_CAP_TIMESLICEERR4,      0x81B02547, "Put capture failed, a timeslice specified on DRV event did not match restricted skip count capabilities")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_ENGINE_START_THREAD_FAILED, 0x81B02548, "Unable to create and launch the AST run thread")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_ENGINE_STOP_THREAD_FAILED,  0x81B02549, "Unable to STOP the running DRV Engine run thread, via a cancel, in a timely manner")

SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_ENGINE_RESET_FAILED,  0x81B0254A, "Unable to RESET the waitcond event used in waiting for complete start of DRV Engine")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_DRV_ENGINE_AST_ERROR, 0x81B0254B, "Call was made into DRV Engine and an error was detected while attempting to wait for full DRV trace start.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_HASFIRED_DRV_ENGINE_ERR_STATE, 0x81B0254C, "Call was made to determine if trigger has fired and the DRV Engine indicated it was in an ERROR state.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DRV_ENGINE_ERR_STATE_ISCOMP,   0x81B0254D, "Call was made and DRV Engine indicated it was in an ERROR state.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_DRV_ENGINE_TIMEOUT,      0x81B0254E, "Call was made to start DRV Engine and a timeout occurred waiting for for full DRV trace start.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_START_DRV_ENGINE_WAIT_ERROR,   0x81B0254F, "Call was made to wait on a start DRV Engine and an unexpected error occurred on the wait call.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_HASFIRED_DRV_ENGINE_BAD_STATE, 0x81B02550, "Call was made to determine if trigger has fired and the DRV Engine indicated it was in an Bad Engine state.")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_INVALID_NULL_POINTER,       0x81B02551, "a NULL pointer was encountered where it is not acceptable")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAME_INVALID_NULL_POINTER, 0x81B02552, "a NULL pointer was encountered where it is not acceptable in CFrame object")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_FRAMEMGR_INVALID_NULL_POINTER, 0x81B02553, "a NULL pointer was encountered where it is not acceptable in CFrameMgr object")

//TraceServer Adapter
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_SVC_ADAPTER_INIT,                   0x81B03001, "new on SlTraceImpl failed")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_SVC_NOT_FOUND,                      0x81B03002, "getOrbManager()->resolveObjectByName failed")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_NO_ORB_MANAGER,                     0x81B03003, "getOrbManager() returns NULL")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_ACTIVATE_TRANSIENT_OBJECT,          0x81B03004, "getOrbManager()->activateTransientObject failed")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_SVC_NARROW,                         0x81B03005, "narrow failed on ITraceServer")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_ACE_SYSTEM_EXCEPTION,               0x81B03006, "an ACE System Exception occured in SlTraceAdapter")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_ACE_ANY_EXCEPTION,                  0x81B03007, "an unknown ACE Exception occured in SlTraceAdapter")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_NULL_ISESSIONCONNECTION,            0x81B03008, "TraceServer returned a null ISessionConnection reference")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_NULL_ISESSIONCONNECTIONEVENTS,      0x81B03009, "the SlTraceSessConnEvents callback object failed to construct an ISessionConnectionEvents servant")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_UNEXPECTED_EXCEPTION,               0x81B0300A, "an unexpected Exception occured in SlTraceAdapter")
SL_TRACE_ERROR_ENUM_GROUPING(A_TRACE_SVC_NO_CONNECT_EP,                  0x81B0300B, "slTraceAdapter can't connect to service, check slhmihost health")

//TraceServer CORBA service
SL_TRACE_ERROR_ENUM_GROUPING(S_TRACE_ACTIVATE_PERSISTENT_OBJECT,         0x81B04001, "getOrbManager()->activatePersistentObject failed")
SL_TRACE_ERROR_ENUM_GROUPING(S_TRACE_BIND_OBJECT_TO_NAME,                0x81B04002, "getOrbManager()->bindObjectToName failed")
SL_TRACE_ERROR_ENUM_GROUPING(S_TRACE_ACTIVATE_TRANSIENT_OBJECT,          0x81B04003, "getOrbManager()->activateTransientObject failed")
SL_TRACE_ERROR_ENUM_GROUPING(S_TRACE_SVC_NARROW,                         0x81B04004, "narrow failed on ISessionConnection")
SL_TRACE_ERROR_ENUM_GROUPING(S_TRACE_ACE_SYSTEM_EXCEPTION,               0x81B04005, "an ACE System Exception occured in SlTraceSvc")
SL_TRACE_ERROR_ENUM_GROUPING(S_TRACE_ACE_ANY_EXCEPTION,                  0x81B04006, "an unknown ACE Exception occured in SlTraceSvc")
SL_TRACE_ERROR_ENUM_GROUPING(S_TRACE_INVALID_NULL_POINTER,               0x81B04007, "a NULL pointer was encountered where it is not acceptable")
SL_TRACE_ERROR_ENUM_GROUPING(S_TRACE_UNEXPECTED_EXCEPTION,               0x81B04008, "an unexpected Exception occured in SlTraceSvc")

//DataManager (LevelOneCache, SignalBuffer, as used by SlTraceSvc)
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DM_FAIL,                            0x81B05001, "DataManager unexpected failure")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DM_INVALID_ARG,                     0x81B05002, "DataManager invalid argument")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DM_INVALID_STATE,                   0x81B05003, "DataManager invalid state")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DM_SQL_ERROR,                       0x81B05004, "DataManager SQL error")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DM_FILE_ERROR,                      0x81B05005, "DataManager database file error, file not found on OpenCache, directory does not exist or file already exists on CreateCache, or file open/locked on DeleteCache")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DM_CANCELED,                        0x81B05006, "DataManager operation canceled by request")
SL_TRACE_ERROR_ENUM_GROUPING(E_TRACE_DM_END_OF_DROPOUT,                  0x81B05101, "End of Dropout")

//TraceSession UI framework
SL_TRACE_ERROR_ENUM_GROUPING(F_TRACE_SIGNAL_BUFFER_ALLOCATION_FAILURE,   0x81B06001, "TraceSession failed to allocate a signal buffer during load trace")
SL_TRACE_ERROR_ENUM_GROUPING(F_TRACE_NO_PERMISSION_TO_OVERWRITE_FILE,    0x81B06002, "TraceSession has no permission to overwrite file during session save")

//Drive Trace
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_NEGATIVE_RECORDING_TIME,	         0x8250C037, "Negative recording time.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_NO_SIGNAL_TO_TRACE,	               0x8250C038, "No signal to trace.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_WARNING_BOUNDED_RECORDING_TIME,    0x0250C034, "Adjusted recording time (bounded between min/mix).")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_INVALID_OBJ_HDL,                        0x82501003, "Invalid DC object handle.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_WARNING_DUPLICATE_SIGNAL,          0x0250C030, "Warning duplicate signal.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_TOO_MANY_SIGNALS,                  0x8250C036, "Too many signals.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_UNEXPECTED_REC_DATA_TYPE,               0x82501007, "Unexpected data type returned from record.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_NOT_TRACEABLE_SIGNAL,              0x8250C032, "Not traceable.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_WARNING_DYNAMIC_INDEX_SIGNAL,      0x0250C033, "Signal has dynamic index, ignoring index.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_INDEX_OUT_OF_BOUND,                     0x8250000C, "Index out of bounds.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_INVALID_STATE,                          0x82500009, "Attemted to call a function while in an invalid state.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MDNR_OUTSIDE_SERVER_DOMAIN,             0x82501001, "MdNr in unknown server domain range.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_BAD_DATA_ITEM_COUNT,                    0x82501008, "Wronge number of data items returned.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_EXTERNAL_ERROR,                         0x82500002, "An external error occurred.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_INVALID_ENUM,                           0x82500008, "Invalid enumeration value.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_OUT_OF_MEMORY,                          0x82500007, "Allocation failed. Out of memory.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_NULL_POINTER,                           0x82500006, "Attempt to access a null pointer.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_UNEXPECTED_ERROR,                       0x82500012, "Programming/Logic problem.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MISSING_MDNAME,                         0x82506004, "Missing md symbol name for acx record.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_INVALID_MACH_REC,                       0x82501006, "Invalid Machine Record.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_INVALID_DRV_REC,                        0x82501004, "Invalid Drive Record.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_DRV_REC_NOT_IN_CONFIG,                  0x82501010, "Drive record is not available with this configuration.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_INVALID_DATA_TYPE,                      0x82500014, "Invalid data type.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_UNDEFINED_ERROR,                        0x82500003, "An undefined error occurred.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_UNKNOWN_SERVER_DOMAIN,                  0x82501002, "Unknown server domain.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_UNKNOWN_LINK_CMD,                       0x82501009, "Unknown link command.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_NO_CHANNEL_FOR_AXIS,                    0x0250B008, "No channel associated with this axis.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_START_CANCEL,                      0x8250C003, "Measurment start is cancelled.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_ALREADY_RUNNING,                   0x8250C01D, "Measurement already running.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_WRONG_DATA_TYPE,                   0x8250C014, "Measurment data returned in wrong data type.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_PRE_TRIGGER_EXCEEDS_RECORDING_TIME,0x8250C040, "Pre-trigger delay is longer than the recording time.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_SERVO_TRACE,                       0x8250C017, "Setup for servo trace failed.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_FG_SETUP,                               0x8250C10A, "FG setup error.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_CLEANUP_FAILED,                    0x8250C019, "Cleaning up the measurement failed.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_USER_ABORT,                        0x8250C001, "Measurment aborted by user.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_INVALID_STATUS,                    0x8250C012, "Measurement status is invalid/wrong state.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_NO_RECORDS,                        0x8250C013, "No measurement data available.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_USER_ABORT_ERROR,                       0x82500011, "The user has aborted a process.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_USER_ABORT_NOT_CLEAN,              0x8250C002, "Measurment not cleanly aborted by user.")\
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_CONDITION_TIMEOUT,                      0x8250000F, "Condition wait timeout.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_MEAS_GENERAL,                           0x8250CD0F, "General: Measurement Error.") //range 0x03-0x0f

//FSM
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_FSM_ALREADY_RUNNING,                    0x82504001, "FSM is already running.")
SL_TRACE_ERROR_ENUM_GROUPING(DRIVE_TRACE_FSM_INVALID_STATE,                      0x82504002, "FSM is in an invalid state.")



//SlCap Error Cover
#define C_TRACE_SL_CAP_OK TRACE_NO_ERROR
#undef SL_CAP_ERROR_ENUM_GROUPING
#define SL_CAP_ERROR_ENUM_GROUPING(N,V,T) SL_TRACE_ERROR_ENUM_GROUPING(C_TRACE_##N,V,T)
#include "slcapenum.h"
#undef SL_CAP_ERROR_ENUM_GROUPING
#undef C_TRACE_SL_CAP_OK

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef SL_TRACE_SRC_ENUM_GROUPING
#define SL_TRACE_SRC_ENUM_GROUPING(N,V,T)
#endif

SL_TRACE_SRC_ENUM_GROUPING(SrcNULL,  0, "The external error source is not specified")
SL_TRACE_SRC_ENUM_GROUPING(SrcQT,    1, "The external error source is Qt")
SL_TRACE_SRC_ENUM_GROUPING(SrcACE,   2, "The external error source is ACE")
SL_TRACE_SRC_ENUM_GROUPING(SrcCORBA, 3, "The external error source is CORBA")
SL_TRACE_SRC_ENUM_GROUPING(SrcSL,    4, "The external error source is Solution Line")

#ifndef SL_TRACE_SEVERITY_ENUM_GROUPING
#define SL_TRACE_SEVERITY_ENUM_GROUPING(N,V,T)
#endif

SL_TRACE_SEVERITY_ENUM_GROUPING(SeverityUNKNOWN, 0, "The error severity is unknown/not specified")
SL_TRACE_SEVERITY_ENUM_GROUPING(SeverityWARNING, 1, "The error is only a warning, normal execution may continue")
SL_TRACE_SEVERITY_ENUM_GROUPING(SeveritySEVERE,  2, "The error is severe, normal execution may not continue")
SL_TRACE_SEVERITY_ENUM_GROUPING(SeverityFATAL,   3, "The error is fatal, the process needs to be restarted")
